config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'account' => 'account#show'
  get 'account/new' => 'account#new'
  get 'account/choose_plan/:id' => 'account#choose_plan', as: 'account_choose_plan'
  post 'account/subscribe' => 'account#subscribe', as: 'account_subscribe'
  delete 'account/cancel' => 'account#cancel', as: 'account_cancel'
  
  resources :projects do
    resources :invites, only: [:new, :create, :destroy]
  end
  
  # bucketloader for mass loading a bucket
  resources :bucket_loaders do
    delete 'destroy_multiple', on: :collection    
    get 'preview(/:id)', to: "bucket_loaders#preview", as: 'preview', on: :collection
    
    member do
      post 'run'
      delete 'cancel'
    end
    
    scope module: :bucket_loader do   
      resources :sources, :load_jobs, only: [:index, :show]
    end
  end
    
  # Source Files
  resources :sources do 
     collection do
         get 'dismiss' => 'sources#dismiss_zips', as: 'dismiss_zips'
         get 'upload' => 'sources#upload'
         get 'status/all' => 'sources#file_status', as: 'all_status'
         get 'status/zips' => 'sources#zips_status', as: 'zips_status' 
         delete 'delete' => 'sources#destroy_multiple'
         
         resources :s3_buckets do
            post 'add' => 's3_buckets#add', format: false, on: :member, as: 'add_file'            
            post 'add_multiple' => 's3_buckets#add_multiple_files', format: false, on: :member, as: 'add_multiple_files'            
            post 'load' => 's3_buckets#load', format: false, on: :member, as: 'load_file'
            get 'search' => 's3_buckets#search', format: false, on: :member 
         end
     end
  end
  
  # Target Databases
  resources :databases do
    patch 'refresh', on: :member
    get 'status', on: :collection
    
    resources :tables
  end  
  
  resources :sql, only: [:index,:show] do
    patch 'database/:database_id', to: 'sql#update_db', on: :member, as: 'db'
    collection do
      resources :scripts do
        resources :queries do
          delete '', to: 'queries#delete_all', on: :collection
        end
      end
    end
  end
  
  # Load Jobs
  get 'loaders/back/(:id)' => 'loaders#back', as: 'loader_back'
  get 'loaders' => 'loaders#index'
  get 'loaders/status/all' => 'loaders#status', as: 'all_status'
  get 'loaders/(:id)/sources' => 'loaders#sources', as: 'loader_sources'
  get 'loaders/(:id)/settings' => 'loaders#settings', as: 'loader_settings'
  get 'loaders/(:id)/transforms' => 'loaders#transforms', as: 'loader_transforms'
  get 'loaders/(:id)/target' => 'loaders#target_table', as: 'loader_target_table'
  get 'loaders/(:id)/summary' => 'loaders#summary', as: 'loader_summary'
  get 'loaders/new' => 'loaders#new', as: 'new_loader'
  get 'loaders/:source_id/load' => 'loaders#load_source', as: 'loader_load_source'
  get 'loaders/:id/edit' => 'loaders#edit', as: 'edit_loader'
  get 'loaders/:id/show' => 'loaders#show', as: 'show_loader'
  delete 'loaders/:id' => 'loaders#destroy', as: 'delete_loader'
  patch 'loaders/:id/sources' => 'loaders#update_sources', as: 'update_loader_sources'
  patch 'loaders/:id/settings' => 'loaders#update_settings', as: 'update_loader_settings'
  patch 'loaders/:id/transform' => 'loaders#update_transform', as: 'update_loader_transform'
  patch 'loaders/:id/target' => 'loaders#update_target', as: 'update_loader_target'
  patch 'loaders/:id/schedule' => 'loaders#update_schedule', as: 'update_loader_schedule'
  get 'loaders/wait' => 'loaders#wait', as: 'loader_wait'
  patch 'loaders/exit' => 'loaders#exit', as: 'exit_loader', format: false
  get 'loaders/exit' => 'loaders#exit_wizzard', as: 'exit_wizzard', format: false
  get 'loaders/:id/run' => 'loaders#run', as: 'loader_run'
  get 'loaders/:id/cancel' => 'loaders#cancel', as: 'loader_cancel'
  post 'loaders/delete' => 'loaders#destroy_multiple', as: 'destroy_loaders'
  post 'loaders/run' => 'loaders#run_multiple', as: 'run_loaders'
  
  get 'dashboard' => 'dashboard#index'
  get 'dashboard/stats' => 'dashboard#stats'
  
  namespace :api do
      scope :hooks, as: 'hooks' do
        post 'stripe', to: 'webhooks#stripe_event'
      end
      
      namespace :xo do
         resources :load_jobs, only: [:update]
         resources :zip_files, only: [:update]
         get 'canary', to: 'load_jobs#canary'
         
         put 'db_requests/query/:id' => 'db_requests#query', as: 'db_query'
         put 'db_requests/schema/:id'=> 'db_requests#schema', as: 'db_schema'
         put 'db_requests/table/:id' => 'db_requests#table', as: 'db_table'
      end
      
      namespace :v1 do
        resources :jobs, only: [:index, :destroy, :show] do
          post ':loader_id/run' => 'jobs#run', on: :collection
        end
        resources :bucket_jobs, only: [:index, :destroy, :show] do
          post ':bucket_loader_id/run' => 'bucket_jobs#run', on: :collection
        end
      end
  end
  
  # Admin routes
  namespace :admin do
    get 'console', to: 'console#index'
    get 'console/:id/show', to: 'console#show'
    get 'console/load_jobs'
    get 'console/queries'
    get 'console/zips'
    get 'console/sources'
    get 'console/databases'
    delete 'cancel_long', to: 'console#cancel_long_running_jobs'
    delete 'cancel_all', to: 'console#cancel_all_jobs'
    delete 'cancel/:id', to: 'console#cancel', as: 'cancel'
    delete 'cancel_unzip/:id', to: 'console#cancel_unzip', as: 'cancel_unzip'
  end
  
  # static high voltage pages
  # this has to be at the bottom of routes file
  # or else it will block all other routes
  get "/*id" => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'
end

app/views/shared/_analytics.html.erb
<% if Rails.env.production? %>    
   	<script>
		// <!-- Facebook Pixel Code -->
	    !function(f,b,e,v,n,t,s)
	    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
	    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
	    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
	    n.queue=[];t=b.createElement(e);t.async=!0;
	    t.src=v;s=b.getElementsByTagName(e)[0];
	    s.parentNode.insertBefore(t,s)}(window,document,'script',
	    'https://connect.facebook.net/en_US/fbevents.js');
	     fbq('init', '969234179830395');
	    fbq('track', 'PageView');	    
	   
	    // <!-- End Facebook Pixel Code -->
	  	
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-88724501-1', 'auto');
	  	  
	  $(document).on('turbolinks:load', function(e){
		  var data = (e.data || e.originalEvent.data);
		  ga("set", "location", data.url)
	  	  ga('send', 'pageview');
		  
		  <% if current_user %>
			  ga('set', 'userId', '<%= current_user.email %>');
			  
			  var new_user_session_flag = $("#new_user_session_flag"); 
			  if(new_user_session_flag.length){
				  ga('send','event', 'users', 'signed_up', '<%= current_user.email %>', 0);
				  fbq('track', 'CompleteRegistration');
			  }
			  
			  var loader_was_run = $("#loader_was_run"); 
			  if(loader_was_run.length){
				  ga('send','event', 'loaders', 'loader_was_run', '<%= current_user.email %>', 0);
			  }				 
			  
		  <% end %>
	  });

	</script>
	<!-- Facebook Pixel Code -->
    <noscript>
     <img height="1" width="1"
    src="https://www.facebook.com/tr?id=969234179830395&ev=PageView
    &noscript=1"/>
    </noscript>
	
<% end %>

app/views/shared/_database_event.html.erb
<% if flash[:event] %>
	<script type="javascript">
		var target = <%= flash[:event] %>;
		if(ga && target){
			ga('send','event', 'targets', target, '<%= current_user.email %>', 0);
		}
	</script>
<% end %>

app/views/shared/_drift.html.erb
	<!-- Start of Async Drift Code -->
	<script>
	!function() {
	  var t;
	  if (t = window.driftt = window.drift = window.driftt || [], !t.init) return t.invoked ? void (window.console && console.error && console.error("Drift snippet included twice.")) : (t.invoked = !0, 
	  t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ], 
	  t.factory = function(e) {
	    return function() {
	      var n;
	      return n = Array.prototype.slice.call(arguments), n.unshift(e), t.push(n), t;
	    };
	  }, t.methods.forEach(function(e) {
	    t[e] = t.factory(e);
	  }), t.load = function(t) {
	    var e, n, o, i;
	    e = 3e5, i = Math.ceil(new Date() / e) * e, o = document.createElement("script"), 
	    o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + i + "/" + t + ".js", 
	    n = document.getElementsByTagName("script")[0], n.parentNode.insertBefore(o, n);
	  });
	}();
	drift.SNIPPET_VERSION = '0.3.1';
	drift.load('brcep9xahwkv');
	</script>
	<!-- End of Async Drift Code -->

app/views/shared/_error_modal.html.erb
<div class="modal fade" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="errorModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="errorModalLabel">Connection Error Message</h4>
      </div>
      <div class="modal-body">
        <pre class="alert alert-danger"> </pre>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-sm btn-default-outline" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="text-center text-muted" style="min-height: 110px;margin-top:10%">
	<%= image_tag('logo-watermark-style.png',class: "img-responsive watermark-logo") %>
	<br />
	<p>Lodr is created and maintained by Vero Analytics, Inc. </p>
	<p>© <%= Date.today.year %> Vero Analytics, Inc.</p>
	<p><%= link_to "Home", root_path %> | <%= link_to "Privacy Policy", page_path('privacy') %> | <%= link_to "Terms & Conditions", page_path('terms') %> </p>
</footer>

<% if session[:tmp_new_user] %>

<div class="hidden" id="new_user_session_flag">
	NEW USER
</div>

<% session[:tmp_new_user] = nil %>
<% end %>

<% if session[:loader_was_run] %>

<div class="hidden" id="loader_was_run">
	loader_was_run
</div>

<% session[:loader_was_run] = nil %>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top nav-app-color">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("favicon/favicon-32x32.png", style: "width:32px"), root_path, class:"navbar-brand lodr-logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navigation">
      <ul class="nav navbar-nav">
		  	
			<% unless current_project.nil? %>
  	          <li class="dropdown dropdown-pop">
  	            <a href="#" class="dropdown-toggle project-sel-btn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
					 &nbsp;<%= current_project.name %> <span class="caret"></span></a>
  	            <ul class="dropdown-menu" >
					<% current_user.projects.each do |p| %>
						<% unless p == current_project %>
	  	              		<li><%= link_to p.name, p %></li>
						<% end %>
  				  	<% end %>
				  
				  <li role="separator" class="divider"></li>
				  
				  <li>
				  	<%= link_to fa_icon("cog", "Project Settings"), "#", data: { toggle: "modal", target: "#project-settings"} %>
				   </li>
 				  <li>
 				  	<%= link_to fa_icon("user-plus", "Invite Users"), "#", data: { toggle: "modal", target: "#invite-users"} %>
 				   </li>
				  
				  <li role="separator" class="divider"></li>
				  <li class="p-x p-b">
					<%= render 'shared/project'%>
				  </li>
				 
  	            </ul>
  	          </li>
			 <% end %>
		  	  
			  <li><%= link_to "Sources", sources_path, class: "nav-item nav-link" %></li>
			  <li><%= link_to "Loaders", loaders_path, class: "nav-item nav-link" %></li>
			  <li><%= link_to "SQL IDE", sql_index_path, class: "nav-item nav-link" %></li> 
			  
  	          <li class="dropdown dropdown-pop">
  	            <a href="#" class="dropdown-toggle more-btn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= fa_icon("bars") %>  &nbsp;More <span class="caret"></span></a>
  	            <ul class="dropdown-menu">
					<li><%= link_to fa_icon("dashboard","Dashboard"), dashboard_path, class: "nav-item nav-link" %></li>
					<li role="separator" class="divider"></li>
	  	            <li><%= link_to en_icon("bucket","S3 Buckets"), s3_buckets_path %></li>
					<li><%= link_to fa_icon("upload","Bucket Loaders"), bucket_loaders_path, class: "nav-item nav-link" %></li>
					<li role="separator" class="divider"></li>
	  				<li><%= link_to fa_icon("database","Databases"), databases_path, class: "nav-item nav-link" %></li>
  	            </ul>
  	          </li>
			  
		    	
				       
      </ul>
	  
	  <% unless current_user.nil? %>
	  <ul class="nav navbar-nav navbar-right">
		  	  <li><%= link_to fa_icon("cloud-upload", "Upload Files"), upload_sources_path, data: {turbolinks: false} %></li>
	          <li class="dropdown dropdown-pop">
	            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= fa_icon("user") %>  &nbsp;<%= clean_user_name %> <span class="caret"></span></a>
	            <ul class="dropdown-menu">
	              <li><%= link_to "Sign Out", destroy_session_path(current_user), method: :delete %></li>
	              <li role="separator" class="divider"></li>
	              <li><%= link_to "Manage Account", account_path %></li>
				  <li><%= link_to "Blog ", 'https://blog.lodr.io', target: "_blank", class: "nav-item nav-link" %></li>
				  <li><%= link_to "Documentation", 'https://blog.lodr.io/tagged/docs', target: "_blank", class: "nav-item nav-link" %></li>			  
				  <li><%= link_to "Video Tutorials", '#', class: "nav-item nav-link", data: {toggle: "modal" , target: "#videoTutorialModal"}%>
				  
				  <% if current_user.admin? %>
	  	              <li role="separator" class="divider"></li>
					  <li><%= link_to "Console", admin_console_path %>
					  <li><%= link_to "Cancel Long Running Jobs", admin_cancel_long_path, method: :delete, data: {confirm: "Are you sure?"} %></li>
	  	              <li><%= link_to "Cancel All Jobs", admin_cancel_all_path, method: :delete, data: {confirm: "Are you sure you want to cancel ALL jobs?"}  %></li>
				  <% end %>
	            </ul>
	          </li>
        </ul>
	  <% end %>	  
	 
	</div><!-- /.navbar-collapse -->
	
	</div><!-- /.container-fluid -->
</nav>

app/views/shared/_project.html.erb
<%= form_for Project.new,  html: { class: "form"} do |f| %>
	 <%= f.text_field :name, value: "", placeholder: "New Project", class: "form-control input-sm" %> 
	<%= f.submit "CREATE PROJECT", class: "btn btn-primary btn-xs w-full", style: "margin-top:4px"%>
<% end %>

app/views/shared/_project_config.html.erb
<div class="modal fade" id="project-settings" tabindex="-1" role="dialog"
	data-remote="<%= edit_project_path(current_project) %>" 
	aria-labelledby="project settings dialog">
  <div class="modal-dialog" role="document">		
	  		  
  </div>
</div>

<div class="modal fade" id="invite-users" tabindex="-1" role="dialog" 
	aria-labelledby="invite users to project dialog" data-remote="<%= new_project_invite_path(current_project) %>" >
  	
	<div class="modal-dialog" role="document">		
	  		  
  	</div>
</div>

app/views/shared/_schedule.html.erb
<% if include_schedule_button %>
	<% if schedulable.scheduled? && schedulable.next_occurrence %>
		<%= link_to fa_icon("calendar-check-o", "Schedule: " + schedulable.schedule_in_words), "#editSchedule", class: "btn btn-success-outline schedule-edit-btn",  data: {toggle: "modal", target: "#scheduleModal"} %>
	<% else %>
		<%= link_to fa_icon("calendar-plus-o", "Add Schedule"), "#editSchedule",  class: "btn btn-success-outline schedule-edit-btn",  data: {toggle: "modal", target: "#scheduleModal"} %>
	<% end %>
<% end %>

<div class="modal fade schedulable" id="scheduleModal" tabindex="-1" role="dialog" aria-labelledby="scheduleModalLabel">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="scheduleModalLabel"><%= fa_icon("calendar")%> Schedule <%= schedulable.class.name.titleize %></h4>
      </div>
	  
      <div class="modal-body p-y-md h-400 over-y-a p-x-md">
		<div class="form-group">
			<%= f.label :schedule_type, "Schedule Frequency", class: "control-label" %> <br />
		  	
      		<%= f.collection_radio_buttons(:schedule_type, schedulable.class.schedule_types, :first, :first, 
      		 	{}, {}) {|b| b.label(:"data-value" => b.value, 
					class: "radio-inline", style: "width:90px;margin-left:5px") { b.radio_button + b.text.titleize.split(" ").last } } %>
			
		</div>
		
		<div class="row" id="start-time-options">					  
		  	<div class="col-sm-4">
				<%= f.label :start_date, "Starts On", class: "control-label" %>
	      		<%= f.date_field :start_date, class: "form-control" %>
			</div>
		  	<div class="col-sm-4">
				<%= f.label :start_time, "Time", class: "control-label" %>
	      		<%= f.time_field :start_time, class: "form-control", 
					value: (schedulable.start_time.class == String ? schedulable.start_time : schedulable.start_time.strftime("%H:%M") ) %>
			</div>
		  	<div class="col-sm-4">
				<%= f.label :time_zone, "Time Zone", class: "control-label" %>
				<%= f.select :time_zone, ActiveSupport::TimeZone::MAPPING.keys, {selected: current_project.time_zone}, { class: "form-control custom-select" } %>
			</div>
		</div>													
		
		<div class="form-inline m-t">
		  <div class="form-group" id="periodic-option">
		    <label for="schedule_period">Runs Every</label>
			<%= f.number_field :schedule_period , class: "form-control form-inline m-x", size: "5", 
				minimum: "1", style: "width:80px;" %>
			<label for="schedule_period">Hour(s)</label>
		  </div>
		</div>
		
					
		<div class="form-group m-t" id="month-of-year-option">
			<hr />	
			<%= f.label :months_of_year, "On Months of Year", class: "control-label" %> <br />
      		<%= f.collection_check_boxes(:months_of_year, array_to_collection(Date::MONTHNAMES), 
				:value, :text, 
      		 	{}, {}) {|b| b.label(:"data-value" => b.value, 
					class: "checkbox-inline", 
					style: "margin-left: 10px;width:100px") { b.check_box + b.text } } %>
		</div>		
		
		<div class="form-group m-t" id="week-of-month-option">
			<hr />	
			<%= f.label :weeks_of_month, "Weeks of Month", class: "control-label" %> <br />
      		<%= f.collection_check_boxes(:weeks_of_month, array_to_collection(Scheduled::WEEKS_OF_MONTH.keys),
				:value, :text,
      		 	{}, {}) {|b| b.label(:"data-value" => b.value, 
					class: "checkbox-inline", 
					style: "margin-left: 10px;width:100px") { b.check_box + b.text.titleize.split(" ").last } } %>
		</div>		
		
		<div class="form-group m-t" id="day-of-week-option">
			<hr />	
			<%= f.label :days_of_week, "On Days of Week", class: "control-label" %> <br />
      		<%= f.collection_check_boxes(:days_of_week, array_to_collection(Date::DAYNAMES), :value, :text, 
      		 	{}, {}) {|b| b.label(:"data-value" => b.value, 
					class: "checkbox-inline", 
					style: "margin-left: 10px;width:100px") { b.check_box + b.text.titleize.split(" ").last } } %>
		</div>									
		
		<div class="row m-t-md" id="day-of-month-option">
			<hr />	
			<%= f.label :day_of_month, "On Day of Month", class: "col-sm-4" %>
			<div class="col-sm-4">
	      		<%= f.select :day_of_month, 1..31, {include_blank: true}, { class: "form-control custom-select"} %>
			</div>
		</div>
		
      </div>
	  
      <div class="modal-footer">
        <button type="button" class="btn btn btn-default-outline schedule-done" data-dismiss="modal">Done</button>
      </div>
	
    </div>
  </div>
</div>

app/views/shared/_static_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top nav-app-color static-header">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigation" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("brand-logo-white-220x60.png"), root_path, class:"navbar-brand lodr-logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navigation">
      <ul class="nav navbar-nav navbar-right">
			<li class="dropdown dropdown-pop">
			   <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" 
					 aria-haspopup="true" aria-expanded="false">Product <span class="caret"></span></a>
			          <ul class="dropdown-menu">
			            <li><%= link_to "Features", page_path('features') %></li>
						<li><%= link_to "Team Cloud Data Warehouse", page_path('articles/team-cloud-data-warehouse') %> </li>
			            <li><%= link_to "Getting Started with Redshift", page_path('articles/getting-started-with-redshift') %> </li>
			  		  	<li><%= link_to "Self Service ETL", page_path('articles/self-service-etl') %> </li>
						<li class="divider"></li>
						<li><%= link_to "Sync S3 Buckets", page_path('articles/sync-s3-buckets-with-redshift') %> </li>
						<li><%= link_to "JSON Extractor", page_path('articles/load-json-files-into-redshift') %> </li>
						<li><%= link_to "Partitioned File Loader", page_path('articles/load-multiple-files-into-the-same-redshift-table') %> </li>
						<li>
							<%= link_to "Skip the COPY Command", page_path('articles/skip-the-copy-command') %> 						</li>
						<li class="divider"></li>
						<li>
							<%= link_to "Release Notes", page_path('articles/lodr-release-notes') %> 						</li>
			          </ul>
		    </li>		  
		  
			
			<li><%= link_to "Pricing", root_path+'pricing', class: "nav-item nav-link" %></li>
			<li><%= link_to "Blog ", 'https://blog.lodr.io', target: "_blank", class: "nav-item nav-link" %></li>
			<li>&nbsp;</li>
 	        <li>	
 			  <% if current_user.nil? %>
 			  	<%= button_to "Sign In", new_user_session_path, class: "navbar-btn btn btn-sm btn-white-outline", method: :get %>
 			 <% end %>
 		   </li>
	  </ul>
	    
	 
	</div><!-- /.navbar-collapse -->
	
	</div><!-- /.container-fluid -->
</nav>

app/views/shared/_tutorial.html.erb
<div class="modal fade" id="videoTutorialModal" tabindex="-1" role="dialog" aria-labelledby="tutorialModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="errorModalLabel">Lodr Video Tutorials</h4>
      </div>
      <div class="modal-body">
      
	  	<div class="row p-a">
			<div class="col-md-4">
				<div class="embed-responsive embed-responsive-16by9">
					<iframe width="100%" height="100%" src="https://www.youtube.com/embed/58KreJ-p7AI" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
			<div class="col-md-4">
				<div class="embed-responsive embed-responsive-16by9">
					<iframe width="100%" height="100%" src="https://www.youtube.com/embed/N8MNJFt7CV4" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
			<div class="col-md-4">
				<div class="embed-responsive embed-responsive-16by9">
					<iframe width="100%" height="100%" src="https://www.youtube.com/embed/0bbNhQdK_Ck" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
		</div>
		
	  	<div class="row p-a">
			<div class="col-md-4">
				<div class="embed-responsive embed-responsive-16by9">
					<iframe width="100%" height="100%" src="https://www.youtube.com/embed/Kn26TRobl-I" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
			<div class="col-md-4">
				<div class="embed-responsive embed-responsive-16by9">
					<iframe width="100%" height="100%" src="https://www.youtube.com/embed/4cDuutSkaNY" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
			<div class="col-md-4">
				<div class="embed-responsive embed-responsive-16by9">
					<iframe width="100%" height="100%" src="https://www.youtube.com/embed/hpyIfdMIpSQ" frameborder="0" allowfullscreen></iframe>
				</div>
			</div>
		</div>	
	    
	  </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-sm btn-default-outline" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>