config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'account' => 'account#show'
  get 'account/new' => 'account#new'
  get 'account/choose_plan/:id' => 'account#choose_plan', as: 'account_choose_plan'
  post 'account/subscribe' => 'account#subscribe', as: 'account_subscribe'
  delete 'account/cancel' => 'account#cancel', as: 'account_cancel'
  
  resources :projects do
    resources :invites, only: [:new, :create, :destroy]
  end
  
  # bucketloader for mass loading a bucket
  resources :bucket_loaders do
    delete 'destroy_multiple', on: :collection    
    get 'preview(/:id)', to: "bucket_loaders#preview", as: 'preview', on: :collection
    
    member do
      post 'run'
      delete 'cancel'
    end
    
    scope module: :bucket_loader do   
      resources :sources, :load_jobs, only: [:index, :show]
    end
  end
    
  # Source Files
  resources :sources do 
     collection do
         get 'dismiss' => 'sources#dismiss_zips', as: 'dismiss_zips'
         get 'upload' => 'sources#upload'
         get 'status/all' => 'sources#file_status', as: 'all_status'
         get 'status/zips' => 'sources#zips_status', as: 'zips_status' 
         delete 'delete' => 'sources#destroy_multiple'
         
         resources :s3_buckets do
            post 'add' => 's3_buckets#add', format: false, on: :member, as: 'add_file'            
            post 'add_multiple' => 's3_buckets#add_multiple_files', format: false, on: :member, as: 'add_multiple_files'            
            post 'load' => 's3_buckets#load', format: false, on: :member, as: 'load_file'
            get 'search' => 's3_buckets#search', format: false, on: :member 
         end
     end
  end
  
  # Target Databases
  resources :databases do
    patch 'refresh', on: :member
    get 'status', on: :collection
    
    resources :tables
  end  
  
  resources :sql, only: [:index,:show] do
    patch 'database/:database_id', to: 'sql#update_db', on: :member, as: 'db'
    collection do
      resources :scripts do
        resources :queries do
          delete '', to: 'queries#delete_all', on: :collection
        end
      end
    end
  end
  
  # Load Jobs
  get 'loaders/back/(:id)' => 'loaders#back', as: 'loader_back'
  get 'loaders' => 'loaders#index'
  get 'loaders/status/all' => 'loaders#status', as: 'all_status'
  get 'loaders/(:id)/sources' => 'loaders#sources', as: 'loader_sources'
  get 'loaders/(:id)/settings' => 'loaders#settings', as: 'loader_settings'
  get 'loaders/(:id)/transforms' => 'loaders#transforms', as: 'loader_transforms'
  get 'loaders/(:id)/target' => 'loaders#target_table', as: 'loader_target_table'
  get 'loaders/(:id)/summary' => 'loaders#summary', as: 'loader_summary'
  get 'loaders/new' => 'loaders#new', as: 'new_loader'
  get 'loaders/:source_id/load' => 'loaders#load_source', as: 'loader_load_source'
  get 'loaders/:id/edit' => 'loaders#edit', as: 'edit_loader'
  get 'loaders/:id/show' => 'loaders#show', as: 'show_loader'
  delete 'loaders/:id' => 'loaders#destroy', as: 'delete_loader'
  patch 'loaders/:id/sources' => 'loaders#update_sources', as: 'update_loader_sources'
  patch 'loaders/:id/settings' => 'loaders#update_settings', as: 'update_loader_settings'
  patch 'loaders/:id/transform' => 'loaders#update_transform', as: 'update_loader_transform'
  patch 'loaders/:id/target' => 'loaders#update_target', as: 'update_loader_target'
  patch 'loaders/:id/schedule' => 'loaders#update_schedule', as: 'update_loader_schedule'
  get 'loaders/wait' => 'loaders#wait', as: 'loader_wait'
  patch 'loaders/exit' => 'loaders#exit', as: 'exit_loader', format: false
  get 'loaders/exit' => 'loaders#exit_wizzard', as: 'exit_wizzard', format: false
  get 'loaders/:id/run' => 'loaders#run', as: 'loader_run'
  get 'loaders/:id/cancel' => 'loaders#cancel', as: 'loader_cancel'
  post 'loaders/delete' => 'loaders#destroy_multiple', as: 'destroy_loaders'
  post 'loaders/run' => 'loaders#run_multiple', as: 'run_loaders'
  
  get 'dashboard' => 'dashboard#index'
  get 'dashboard/stats' => 'dashboard#stats'
  
  namespace :api do
      scope :hooks, as: 'hooks' do
        post 'stripe', to: 'webhooks#stripe_event'
      end
      
      namespace :xo do
         resources :load_jobs, only: [:update]
         resources :zip_files, only: [:update]
         get 'canary', to: 'load_jobs#canary'
         
         put 'db_requests/query/:id' => 'db_requests#query', as: 'db_query'
         put 'db_requests/schema/:id'=> 'db_requests#schema', as: 'db_schema'
         put 'db_requests/table/:id' => 'db_requests#table', as: 'db_table'
      end
      
      namespace :v1 do
        resources :jobs, only: [:index, :destroy, :show] do
          post ':loader_id/run' => 'jobs#run', on: :collection
        end
        resources :bucket_jobs, only: [:index, :destroy, :show] do
          post ':bucket_loader_id/run' => 'bucket_jobs#run', on: :collection
        end
      end
  end
  
  # Admin routes
  namespace :admin do
    get 'console', to: 'console#index'
    get 'console/:id/show', to: 'console#show'
    get 'console/load_jobs'
    get 'console/queries'
    get 'console/zips'
    get 'console/sources'
    get 'console/databases'
    delete 'cancel_long', to: 'console#cancel_long_running_jobs'
    delete 'cancel_all', to: 'console#cancel_all_jobs'
    delete 'cancel/:id', to: 'console#cancel', as: 'cancel'
    delete 'cancel_unzip/:id', to: 'console#cancel_unzip', as: 'cancel_unzip'
  end
  
  # static high voltage pages
  # this has to be at the bottom of routes file
  # or else it will block all other routes
  get "/*id" => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
         
  has_many :source_files, dependent: :destroy
  has_many :loaders, dependent: :destroy
  has_many :databases, dependent: :destroy
  has_many :load_jobs, dependent: :destroy
  has_many :s3_buckets, dependent: :destroy
  has_many :zip_files, dependent: :destroy
  has_many :scripts, dependent: :destroy
  has_many :bucket_loaders, dependent: :destroy
  
  has_many :project_users, dependent: :destroy
  has_many :projects,  -> { distinct }, through: :project_users
  
  # Do not dependent destroy this.
  # It will be taken care of Via Scripts
  has_many :queries
  has_one :subscription, dependent: :destroy
  
  validates :first_name, :last_name, presence: true
  
  before_create :generate_token
  after_create :subscribe_bootstrap, :create_default_project
  before_save :update_subscription_parameters, unless: :new_record?
  
  before_destroy :destroy_owned_projects
    
  def generate_token
    loop do
        self.api_access_key = Devise.friendly_token
        break unless self.class.exists?(api_access_key: self.api_access_key  )
    end
  end
  
  # Configure devise to use delayed_job
  # as the backend for mail delivery
  # see more @ https://github.com/plataformatec/devise#activejob-integration
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
  
  def full_name
    "#{first_name} #{last_name}"
  end
    
  # Cancels any existing subscription and
  # moves user into the free plan. Whenever
  # users cancel plans or signs up we will
  # add them to the free tier
  def subscribe_bootstrap
    sub = self.subscription
    
    if sub && !sub.new_record?
      sub.cancel
    elsif sub.nil?
      sub = Subscription.new user: self, plan: Plan.bootstrap, 
                reset_at: Time.now, rows_processed: 0, queries_run: 0
      sub.save
    end
    
  end
  
  def self.search(search)
    unless search.blank?
      where('lower(email) LIKE ?', "%#{search.downcase}%")
    else
      order(created_at: :desc)
    end
  end
  
  def create_default_project    
    unless Project.exists?(owner_id: self.id)
      p = Project.create owner_id: self.id, name: "My Project"
    end
  end
  
  def destroy_owned_projects
    p = Project.where(owner_id: self.id)
    p.update_all(owner_id: -99)
    p.destroy_all
  end
  
  def update_subscription_parameters
    self.subscription.update_period_and_usage
  end  
end

app/controllers/bucket_loader/load_jobs_controller.rb
class BucketLoader::LoadJobsController < ApplicationController
  
end

app/controllers/bucket_loader/sources_controller.rb
class BucketLoader::SourcesController < ApplicationController
  
  def index
  end
  
end

app/controllers/bucket_loaders_controller.rb
class BucketLoadersController < ApplicationController

  def index
    if params[:loaders]
      lds = JSON.parse(params[:loaders])
      @bucket_loaders = current_project.bucket_loaders
            .where(id: lds)
            .order("greatest(created_at,updated_at) desc")
    else
      @bucket_loaders = current_project.bucket_loaders
            .order("greatest(created_at,updated_at) desc")
            .paginate(:page => params[:page], :per_page => @per_page)
            .search(params[:search])
    end
    
    respond_to do |format|
      format.js 
      format.html
      format.all {render json: @bucket_loaders}
    end
  end
  
  def new
    if params[:bucket_loader_id]
      @bucket_loader = current_project.bucket_loaders.find(params[:bucket_loader_id]).dup
    else
      shortcuts = params[:bucket_loader].nil? ? {} : bucket_loader_params
      @bucket_loader = BucketLoader.new(shortcuts)
    end    
  end
  
  def create
    @bucket_loader = BucketLoader.new(bucket_loader_params)
    @bucket_loader.user = current_user
    @bucket_loader.project = current_project
    if @bucket_loader.save
      schedule_load(@bucket_loader) 
      redirect_to bucket_loaders_path, notice: "Saved bucket loader #{@bucket_loader.name}"
    else
      render 'new'
    end
  end
  
  def update
    @bucket_loader = current_project.bucket_loaders.find params[:id]
    if @bucket_loader.update(bucket_loader_params)
      schedule_load(@bucket_loader)      
      redirect_to bucket_loaders_path, notice: "Saved bucket loader #{@bucket_loader.name}"
    else
      render 'edit'
    end
  end
  
  def show
     @bucket_loader = current_project.bucket_loaders.find params[:id]
     
     @histories = @bucket_loader.bucket_load_histories
           .order("greatest(created_at,updated_at) desc")
           .paginate(:page => params[:history_page], :per_page => @per_page)
    
     @loaders = @bucket_loader.loaders
           .order("greatest(created_at,updated_at) desc")
           .paginate(:page => params[:loader_page], :per_page => @per_page)
     
     @sources = @bucket_loader.source_files
           .order("greatest(created_at,updated_at) desc")
           .paginate(:page => params[:sources_page], :per_page => @per_page)
  end
  
  def edit
    @bucket_loader = current_project.bucket_loaders.find params[:id]
  end
  
  def preview
    if params[:bucket_loader]
      @bucket_loader = BucketLoader.new bucket_loader_params
    else
      @bucket_loader = current_project.bucket_loaders.find params[:id]
    end
   
    @preview = @bucket_loader.preview
  end
  
  def run
    @bucket_loader = current_project.bucket_loaders.find params[:id]
    
    unless @bucket_loader.is_running?
      @bh = BucketLoadHistory.create(bucket_loader: @bucket_loader, status: :queued)    
      BucketLoadJob.perform_later @bh
    end
    
    redirect_back fallback_location: bucket_loaders_path, notice: "Bucket loader #{@bucket_loader.name} is running..."
  end
  
  def cancel
    @bucket_loader = current_project.bucket_loaders.find params[:id]
    @bucket_loader.cancel
    redirect_back fallback_location: bucket_loaders_path, notice: "Bucket loader #{@bucket_loader.name} was cancelled..."
  end
  
  def destroy
    @bucket_loader = current_project.bucket_loaders.find params[:id]
    @bucket_loader.cancel if @bucket_loader.is_running?
    @bucket_loader.destroy
    redirect_to bucket_loaders_path, notice: "Bucket loader #{@bucket_loader.name} and related loaders and sources were deleted..."
  end
  
  def destroy_multiple
    current_project.bucket_loaders.where(id: params[:bucket_loader_ids]).destroy_all
    redirect_to bucket_loaders_path, notice: "Selected bucket loaders were deleted..."
  end
  
  private
  
  def bucket_loader_params
    params.require(:bucket_loader).permit(:name,:prefix,:file_filter,
      :includes_header,:delimiter,:quote_char, :file_mapping_type,
      :load_new_files_only, :load_type, :target_table_prefix, :target_table_suffix,
      :notify_type, :notification_emails, :schedule_type, :schedule_definition,
      :s3_bucket_id, :database_id, :pre_sql_id, :post_sql_id,
      :start_date, :start_time, :time_zone, :schedule_period, :schedule_type,
      { :months_of_year => [] }, { :weeks_of_month => [] },
      { :days_of_week => [] }, :day_of_month)
  end
  
  def schedule_load(bucket_loader)
    bucket_loader.bucket_load_histories.where(status: :scheduled).destroy_all
    if bucket_loader.scheduled?      
      @bh = BucketLoadHistory.create(bucket_loader: bucket_loader, status: :scheduled)
      BucketLoadJob.set(wait_until: bucket_loader.next_occurrence).perform_later @bh  
    end    
  end
end

app/helpers/bucket_loaders_helper.rb
module BucketLoadersHelper
  
  def humanize_seconds secs
    return "" if secs.nil? 
    [[60, :secs], [60, :mins], [24, :hrs], [1000, :days]].map{ |count, name|
      if secs > 0
        secs, n = secs.divmod(count)
        "#{n.to_i} #{name}"
      end
    }.compact.reverse.join(' ')
  end
  
end

app/views/bucket_loaders/_bucket_loader.html.erb
<div class="row">
	<div class="col-md-4">
		
		<div class="row">
			<div class="col-sm-3 text-center icon-ctr checkbox-inline">
				<%= check_box_tag 'bucket_loader_ids[]', loader.id, false, class: "input-lg"%>	 
				
				<% if loader.scheduled? %>
  				  <span class="fa-stack fa-lg text-warning" title="job is ready to be run">
  				    <i class="fa fa-circle-thin fa-stack-2x"></i>
  					<i class="fa fa-calendar fa-stack-1x"></i>
  				  </span>
				<% else %>
  				  <span class="fa-stack fa-lg text-info" title="job is ready to be run">
  				    <i class="fa fa-circle-thin fa-stack-2x"></i>
  					<i class="fa fa-upload fa-stack-1x"></i>
  				  </span>
				<% end %> 					  
			</div>
			<div class="col-sm-9">
				<h4 class="title"><%= link_to loader.name, bucket_loader_path(loader) %></h4>
				<p class="text-muted"><i class="fa fa-clock-o" aria-hidden="true"></i>
					<% if loader.last_run %> 
						ran <%= time_ago_in_words(loader.last_run.created_at) %> ago
					<% else %>
						edited <%= time_ago_in_words(loader.updated_at) %> ago
					<% end %>
				</p>
				
				<% if loader.scheduled? %>
					<p class="text-info"><i class="fa fa-clock-o"></i>&nbsp; 
						next run on <%= loader.next_occurrence.strftime('%B %d, %Y %I:%M %p %Z') %> </p>
				<% end %>
 			   <% if loader.last_run %>
 				<div class="loader-status m-b">
 					<% if loader.last_run.failed? %>
 						<span class="label label-danger <%= loader.last_run.status %>" 
 							data-loader-id="<%= loader.id %>" >Failed</span>
 					<% elsif loader.last_run.running? %>
 						<span class="label label-primary <%= loader.last_run.status %>"
 							data-loader-id="<%= loader.id %>"  ><%= loader.last_run.status.titleize %></span>&nbsp;<i class="fa fa-spinner fa-spin"></i>		<% elsif loader.last_run.done? %>
 						<span class="label label-success <%= loader.last_run.status %>" 
 							data-loader-id="<%= loader.id %>" >Done</span> 
					<% elsif loader.last_run.cancelled? %>
 						<span class="label label-warning <%= loader.last_run.status %>" 
 							data-loader-id="<%= loader.id %>" >Cancelled</span>					
 					<% else %>
 						<span class="label label-info <%= loader.last_run.status %>"
 							data-loader-id="<%= loader.id %>" > <%= loader.last_run.status.titleize %> </span>
 					<% end %>
 				</div>				
 				<% end %>
				
			</div>
		</div>
				
	</div> 
	
	<div class="col-md-8">
		<div class="row">
			<div class="col-md-3 titled-label">
				<% if loader.s3_bucket.nil? %>
					<label class="label" style="color:#e40505;">BUCKET</label>
					<h5 class="text-danger"><%= link_to "FIXME", edit_bucket_loader_path(loader) %></h5>
				<% else %>
					<label class="label" >BUCKET</label>
					<h5><%= link_to loader.s3_bucket.bucket_name, loader.s3_bucket %></h5>
				<% end %>	
			</div>
	
			<div class="col-md-3 titled-label">
				<label class="label" >PREFIX</label>
				<h5><%= loader.prefix || "NONE" %></h5>			
			</div>
	
			<div class="col-md-3 titled-label">
				<label class="label" >MAPPING</label>
				<h5><%= loader.file_mapping_type.titleize %></h5>	
			</div>
	
			<div class="col-md-3 titled-label">
				
				<% if loader.database.nil? %>
					<label class="label"  style="color:#e40505;">DATABASE</label>
					<h5 class="text-danger"><%= link_to "FIXME", edit_bucket_loader_path(loader) %></h5>
				<% else %>
					<label class="label" >DATABASE</label>
					<h5><%= loader.database.name %></h5>
				
				<% end %>
			</div>
		</div>
		
		<% if loader.last_run %>
		<div class="row">
			
			<div class="col-md-3 titled-label">
				<label class="label" >FILES</label>
				<h5><%= loader.last_run.files_to_load %></h5>	
			</div>
			
			<div class="col-md-3 titled-label">
				<label class="label" >SUCCEEDED / FAILED</label>
				<h5><%= loader.last_run.succeeded_files %> / <%= loader.last_run.failed_files %></h5>	
			</div>
			
			<div class="col-md-5 titled-label">
				<label class="label" >PROGRESS</label>
				<div class="progress">
					<% if loader.last_run.failed?  %>
    	  				  <div class="progress-bar progress-bar-danger" 
    						  role="progressbar" aria-valuenow="<%= loader.last_run.percent_done * 100 %>" 
    						  aria-valuemin="0" aria-valuemax="100" style="width: <%= loader.last_run.percent_done * 100 %>%;">
    	  				    <%= loader.last_run.percent_done * 100 %>%
    	  				  </div>
					<% elsif loader.last_run.cancelled?%>
  	  				  <div class="progress-bar progress-bar-warning" 
  						  role="progressbar" aria-valuenow="<%= loader.last_run.percent_done * 100 %>" 
  						  aria-valuemin="0" aria-valuemax="100" style="width: <%= loader.last_run.percent_done * 100 %>%;">
  	  				    <%= loader.last_run.percent_done * 100 %>%
  	  				  </div>
					<% else %>
	  				  <div class="progress-bar <%= loader.last_run.done? ? 'progress-bar-success' : 'progress-bar-striped' %> " 
						  role="progressbar" aria-valuenow="<%= loader.last_run.percent_done * 100 %>" 
						  aria-valuemin="0" aria-valuemax="100" style="width: <%= loader.last_run.percent_done * 100 %>%;">
	  				    <%= loader.last_run.percent_done * 100 %>%
	  				  </div>
					<% end %>
				  
				</div>
			</div>

		</div>
		<% end %>
		
	</div>
	
		
</div>


<div class="row">
	<div class="col-md-offset-1 col-md-7">
					
		<div class="btn-group btn-group-sm m-b" role="group" aria-label="...">
			<% if loader.last_run && loader.last_run.running? %>
				<%= link_to fa_icon("ban", "Cancel"), cancel_bucket_loader_path(loader), method: :delete, class:"btn btn-danger" ,style: "text-align:left;" %>
			<% else %>
				<%= link_to fa_icon("play-circle", "Run"), run_bucket_loader_path(loader),method: :post, class:"btn btn-default" ,style: "text-align:left;" %>
			<% end %>
			
			<%= link_to fa_icon("eye", "View"), bucket_loader_path(loader), class:"btn btn-default" ,style: "text-align:left;" %>
			<%= link_to(fa_icon("pencil", "Edit"), edit_bucket_loader_path(loader), class: "btn btn-default",style: "text-align:left;") %>
			<%= link_to(fa_icon("clone", "Copy"), new_bucket_loader_path(bucket_loader_id: loader.id), class: "btn btn-default",style: "text-align:left;") %>
			<%= link_to(fa_icon("trash", "Delete"), bucket_loader_path(loader), 
				class: "btn btn-default",style: "text-align:left;",
				data: {confirm: "Are you sure you want to delete this loader?"}, method: :delete) %>		
		</div>
		
	</div>
	
</div>

app/views/bucket_loaders/_preview.html.erb
<a class="btn btn-primary-outline m-b" onclick="lodr.bucket_loader.getPreview();return false;"><i class="fa fa-refresh"></i> Refresh Preview</a>

<% if @preview %>
	<div class="bucket_loader_preview p-a over-x-a">
		<h4>Preview of Generated Tables and File Mappings</h4>
		<p class="help-block m-b">Only the first 10 target tables are shown</p>
		<% @preview.each do |key, value| %>
		<div class="bucket_loader_preview_table m-b">
				<p ><i class="fa fa-table"></i> &nbsp;<%= key %></p>
					<ul class="fa-ul p-l-lg">
						<% value.each do |v| %>
							<li ><i class="fa-li fa fa-file-o"></i> <%= v %></li>
						<% end %>
					</ul>	
				
		</div>
		<% end %>
		
	</div>
<% else %>
	<div class="alert alert-danger"><%= @bucket_loader.errors.full_messages.join("\n") %></div>
<% end %>

app/views/bucket_loaders/edit.html.erb
<div class="row">
	<div class="col-sm-6">
		<h1 class="page-title">Editing Bucket Loader</h1>
		<%= render partial: 'form', locals: {loader: @bucket_loader} %>
	</div>
	<div class="col-sm-6 bucket_loader_preview_section p-a-lg" data-preview-path="<%= preview_bucket_loaders_path(@bucket_loader) %>">
		
	</div>
</div>

app/views/bucket_loaders/index.html.erb
<div class="m-y loader-tabs">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation"><%= link_to "Loaders", loaders_path %> </li>
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Bucket Loaders</a></li>
  </ul>

  <div class="tab-content p-a-md p-x-lg">
	  
	  
<h1 class="page-title">Bucket Loaders</h1>

<div class="row">
	<div class="col-sm-6">
		<div class="btn-toolbar">
			<a class="btn btn-default check-all" data-checked="false" data-check-all-target=".check-enable"> <i class="fa fa-square-o fa-1x" aria-hidden="true"></i></a>
			<%= link_to ("<span class=\"icon icon-bucket\"></span> New Bucket Loader").html_safe, new_bucket_loader_path, 
							class: "btn btn-sm btn-primary" %>
			<%= link_to fa_icon("trash", "Delete Selected"), "#", 
				class: "btn btn-sm btn-danger-outline hidden check-enable",
				data: {"check-all-form" => "#destroy_loaders" } %>
		</div>
	</div>
	<div class="col-sm-6 text-right">
		<%= form_tag(bucket_loaders_path, method: "get", class: "form-inline") do %>
		<div class="form-group">
		  <%= text_field_tag(:search, params[:search], class: "form-control", placeholder: "search bucket loaders") %>
		</div>
		  <%= submit_tag "Search", class: "btn btn-sm btn-default-outline" %>
		<% end %>
	</div>
</div>

<br />

<%= form_tag destroy_multiple_bucket_loaders_path, id: "destroy_loaders", method: :delete do %>
<% end %>


<%= form_tag "", id: "main-check-all-form" do %>
<div class="lodr-table list-group">
	
	<% if @bucket_loaders.count ==0  %>
		<% if params[:search].blank? %>
			<div class="embed-responsive embed-responsive-16by9">
				<iframe width="100%" height="100%" src="https://www.youtube.com/embed/Kn26TRobl-I" frameborder="0" allowfullscreen></iframe>
			</div>
		<% else %>
			<div class="alert p-a-lg alert-warning">
				<i class="fa fa-exclamation-triangle"></i>
				<strong>Oh oh,</strong> we could not find any bucket loaders with a name containing <strong><%= params[:search] %></strong>
			</div>
		<% end %>
	<% end %>
	
	<% @bucket_loaders.each do |loader| %>
		<div class="list-group-item input-file" id="bucket_loader_<%= loader.id %>" data-loader-id="<%= loader.id %>" >
			<%= render partial: 'bucket_loader', locals: {loader: loader} %>
		</div>
	<% end %>
</div>
<% end %>

</div> <!-- end tab content -->
</div> <!-- end tabs -->

<%= will_paginate @loaders %>

<% if @bucket_loaders.size > 0 %>
	<%= select_tag :per_page, options_for_select([10,25,50,100], @per_page),
			class: "form-control pull-right", style: "width:50px",
	       :onchange => "if(this.value){window.location=window.location+'?&per_page='+this.value;}" %>
<% end %>

<%= render 'shared/error_modal' %>

app/views/bucket_loaders/index.js.erb
<% @bucket_loaders.each do |loader| %>
	$("#bucket_loader_<%= loader.id %>").html(
		"<%=raw escape_javascript(render partial: 'bucket_loader', locals: {loader: loader} )%>"
	);
<% end %> 

app/views/bucket_loaders/new.html.erb
<div class="row">
	<div class="col-sm-6">
		<h1 class="page-title">New Bucket Loader</h1>
		<%= render partial: 'form', locals: {loader: @bucket_loader} %>
	</div>
	<div class="col-sm-6 bucket_loader_preview_section p-a-lg"  data-preview-path="<%= preview_bucket_loaders_path(@bucket_loader) %>">
		
	</div>
</div>

app/views/bucket_loaders/preview.html.erb
<%= render 'preview' %>

app/views/bucket_loaders/preview.js.erb
$(".bucket_loader_preview_section").html("<%= escape_javascript(render 'preview') %> ");