config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'account' => 'account#show'
  get 'account/new' => 'account#new'
  get 'account/choose_plan/:id' => 'account#choose_plan', as: 'account_choose_plan'
  post 'account/subscribe' => 'account#subscribe', as: 'account_subscribe'
  delete 'account/cancel' => 'account#cancel', as: 'account_cancel'
  
  resources :projects do
    resources :invites, only: [:new, :create, :destroy]
  end
  
  # bucketloader for mass loading a bucket
  resources :bucket_loaders do
    delete 'destroy_multiple', on: :collection    
    get 'preview(/:id)', to: "bucket_loaders#preview", as: 'preview', on: :collection
    
    member do
      post 'run'
      delete 'cancel'
    end
    
    scope module: :bucket_loader do   
      resources :sources, :load_jobs, only: [:index, :show]
    end
  end
    
  # Source Files
  resources :sources do 
     collection do
         get 'dismiss' => 'sources#dismiss_zips', as: 'dismiss_zips'
         get 'upload' => 'sources#upload'
         get 'status/all' => 'sources#file_status', as: 'all_status'
         get 'status/zips' => 'sources#zips_status', as: 'zips_status' 
         delete 'delete' => 'sources#destroy_multiple'
         
         resources :s3_buckets do
            post 'add' => 's3_buckets#add', format: false, on: :member, as: 'add_file'            
            post 'add_multiple' => 's3_buckets#add_multiple_files', format: false, on: :member, as: 'add_multiple_files'            
            post 'load' => 's3_buckets#load', format: false, on: :member, as: 'load_file'
            get 'search' => 's3_buckets#search', format: false, on: :member 
         end
     end
  end
  
  # Target Databases
  resources :databases do
    patch 'refresh', on: :member
    get 'status', on: :collection
    
    resources :tables
  end  
  
  resources :sql, only: [:index,:show] do
    patch 'database/:database_id', to: 'sql#update_db', on: :member, as: 'db'
    collection do
      resources :scripts do
        resources :queries do
          delete '', to: 'queries#delete_all', on: :collection
        end
      end
    end
  end
  
  # Load Jobs
  get 'loaders/back/(:id)' => 'loaders#back', as: 'loader_back'
  get 'loaders' => 'loaders#index'
  get 'loaders/status/all' => 'loaders#status', as: 'all_status'
  get 'loaders/(:id)/sources' => 'loaders#sources', as: 'loader_sources'
  get 'loaders/(:id)/settings' => 'loaders#settings', as: 'loader_settings'
  get 'loaders/(:id)/transforms' => 'loaders#transforms', as: 'loader_transforms'
  get 'loaders/(:id)/target' => 'loaders#target_table', as: 'loader_target_table'
  get 'loaders/(:id)/summary' => 'loaders#summary', as: 'loader_summary'
  get 'loaders/new' => 'loaders#new', as: 'new_loader'
  get 'loaders/:source_id/load' => 'loaders#load_source', as: 'loader_load_source'
  get 'loaders/:id/edit' => 'loaders#edit', as: 'edit_loader'
  get 'loaders/:id/show' => 'loaders#show', as: 'show_loader'
  delete 'loaders/:id' => 'loaders#destroy', as: 'delete_loader'
  patch 'loaders/:id/sources' => 'loaders#update_sources', as: 'update_loader_sources'
  patch 'loaders/:id/settings' => 'loaders#update_settings', as: 'update_loader_settings'
  patch 'loaders/:id/transform' => 'loaders#update_transform', as: 'update_loader_transform'
  patch 'loaders/:id/target' => 'loaders#update_target', as: 'update_loader_target'
  patch 'loaders/:id/schedule' => 'loaders#update_schedule', as: 'update_loader_schedule'
  get 'loaders/wait' => 'loaders#wait', as: 'loader_wait'
  patch 'loaders/exit' => 'loaders#exit', as: 'exit_loader', format: false
  get 'loaders/exit' => 'loaders#exit_wizzard', as: 'exit_wizzard', format: false
  get 'loaders/:id/run' => 'loaders#run', as: 'loader_run'
  get 'loaders/:id/cancel' => 'loaders#cancel', as: 'loader_cancel'
  post 'loaders/delete' => 'loaders#destroy_multiple', as: 'destroy_loaders'
  post 'loaders/run' => 'loaders#run_multiple', as: 'run_loaders'
  
  get 'dashboard' => 'dashboard#index'
  get 'dashboard/stats' => 'dashboard#stats'
  
  namespace :api do
      scope :hooks, as: 'hooks' do
        post 'stripe', to: 'webhooks#stripe_event'
      end
      
      namespace :xo do
         resources :load_jobs, only: [:update]
         resources :zip_files, only: [:update]
         get 'canary', to: 'load_jobs#canary'
         
         put 'db_requests/query/:id' => 'db_requests#query', as: 'db_query'
         put 'db_requests/schema/:id'=> 'db_requests#schema', as: 'db_schema'
         put 'db_requests/table/:id' => 'db_requests#table', as: 'db_table'
      end
      
      namespace :v1 do
        resources :jobs, only: [:index, :destroy, :show] do
          post ':loader_id/run' => 'jobs#run', on: :collection
        end
        resources :bucket_jobs, only: [:index, :destroy, :show] do
          post ':bucket_loader_id/run' => 'bucket_jobs#run', on: :collection
        end
      end
  end
  
  # Admin routes
  namespace :admin do
    get 'console', to: 'console#index'
    get 'console/:id/show', to: 'console#show'
    get 'console/load_jobs'
    get 'console/queries'
    get 'console/zips'
    get 'console/sources'
    get 'console/databases'
    delete 'cancel_long', to: 'console#cancel_long_running_jobs'
    delete 'cancel_all', to: 'console#cancel_all_jobs'
    delete 'cancel/:id', to: 'console#cancel', as: 'cancel'
    delete 'cancel_unzip/:id', to: 'console#cancel_unzip', as: 'cancel_unzip'
  end
  
  # static high voltage pages
  # this has to be at the bottom of routes file
  # or else it will block all other routes
  get "/*id" => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'
end

app/controllers/databases_controller.rb
class DatabasesController < ApplicationController
  skip_before_action :on_boarding_user_route  
  before_action :set_loader, only: [:new, :create, :update]
  layout :set_loader_layout
  
  def index
      @databases = current_project.databases
  end
  
  def new      
      @database = Database.new
  end
  
  def refresh
    @database = current_project.databases.find params[:id]
    @database.schema_fetching!
    RemoteDbRequestJob.perform_later(@database, "schema")
    
    respond_to do |format|
        format.html { redirect_to sql_index_path, notice: "Refreshing database schema..."}
        format.js { }
    end
  end
  
  def show    
    respond_to do |format|
        format.html { redirect_to edit_database_path(params[:id]) }
        format.js { @database = current_project.databases.find params[:id] }
    end
  end
  
  def edit
      @database = current_project.databases.find params[:id]
  end
  
  def create
      @database = Database.new(database_params)
      @database.user = current_user
      @database.project = current_project
      
      @database.properties = get_props_json
      if @database.save
          RemoteDbRequestJob.perform_now(@database, "test")
          RemoteDbRequestJob.perform_later(@database, "schema")
          
          if @database.failed?            
            if @database.test_error.include?("Net::ReadTimeout")
              @database.update_attributes(test_connection_status: :testing, test_error: nil)
              RemoteDbRequestJob.perform_later(@database, "test", 180)
              if @loader
                redirect_to edit_loader_path(@loader)
              else
                redirect_to databases_path
              end
            else
              flash.now[:alert] = "<h4><strong class='text-danger'>Failed to Connect</strong></h4> <p>Please ensure the connection info is correct. Perhaps you need to whitelist our IP address or configure SSL properties.</p><br/> <p>#{@database.test_error[0..300]}</p>"
              render 'new'
            end            
          else
            flash[:event] = "target created"
            if @loader
              redirect_to edit_loader_path(@loader)
            else
              redirect_to databases_path
            end
          end
          
      else
          render 'new'
      end
  end
  
  def update
      @database = current_project.databases.find params[:id]
      @database.assign_attributes(database_params)
      @database.properties = get_props_json
      if @database.save
          RemoteDbRequestJob.perform_now(@database, "test") if @database.testing?
          RemoteDbRequestJob.perform_later(@database, "schema")
          
          if @database.failed?
            if @database.test_error.include?("Net::ReadTimeout")
              @database.update_attributes(test_connection_status: :testing, test_error: nil)
              RemoteDbRequestJob.perform_later(@database, "test", 180)
              redirect_to databases_path
            else                          
              flash.now[:alert] = "<h4><strong class='text-danger'>Failed to Connect</strong></h4> <p>Please ensure the connection info is correct. Perhaps you need to whitelist our IP address or configure SSL properties.</p><br/> <p>#{@database.test_error[0..300]}</p>"
              render 'new'
            end
          else
            redirect_to databases_path
          end                    
          
      else
          render 'new'
      end
  end
  
  def destroy
     @database = current_project.databases.find params[:id]
     @database.destroy 
      
      respond_to do |format|
        format.html {redirect_to databases_path}
        format.all {render text: "#{@database.name} was deleted"}
      end
  end
  
  def status
      return redirect_to databases_path, alert: "Missing `Targets` Parameter. i.e targets=[1,2,3]" if params[:targets].nil?
    
      fil = JSON.parse(params[:targets])
      @databases = Database.where(id: fil, project_id: current_project.id)
    
      respond_to do |format|
        format.js
        format.html {redirect_to databases_path}
        format.all {render json: @databases}
      end 
  end
  
  private
  
  def database_params
     tp = params.require(:database).permit(
         :name, :user_name, :password, :db_name,
         :jdbc_url, :port, :server
     )
     
     tp.delete(:password) if tp[:password].blank?
     return tp
  end
  
  def get_props_json
      return nil if params[:props].nil?
      props = {}
      params[:props].each_pair do |key,val|
          if key.starts_with? "key"
             parts = key.split("_")
             
             if parts.size == 2
                 actual_val = params[:props]["val_#{parts[1]}"]
                 props[val] = actual_val unless actual_val.nil? || actual_val.empty?
             end
          end
      end
      
      props.to_json || nil     
  end
  
  def set_loader
    if session[:loader_id]
      @loader = current_project.loaders.where(id: session[:loader_id]).first
    end
  end
  
  def set_loader_layout
    if @loader
      'loaders'
    else
      'application'
    end
  end
  
end

app/views/databases/_browser.html.erb
<div class="browser-panel">
	<div class="browser-panel-header">
		
		<span class="icon icon-database db <%= @database.test_connection_status %>"
				data-toggle="tooltip" data-placement="right" 
				title="<%= @database.failed? ? @database.test_error : @database.testing? ? 'Testing...' : 'Connected' %>" > </span>
		 
		<span class="header-label"> <%= @database.name %> </span>
				
		<div class="dropdown btn-group pull-right browser-menu">
		  <button class="btn dropdown-toggle" type="button" id="db-dropdown" 
		  	data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
		    
		    <i class="fa fa-chevron-down" aria-hidden="true"></i>
		  </button>
	
			<ul class="dropdown-menu" aria-labelledby="db-drop-down">
				<li><%= link_to "Edit Connection", edit_database_path(@database), id: "edit-db-conn" %> </li>			
				<li><%= link_to "Refresh", refresh_database_path(@database), remote: true, 
					method: :patch, id: "refresh-db-schema" %> </li>
				
				<li role="separator" class="divider"></li>
				<li class="dropdown-submenu">
			        <a class="submenu" tabindex="-1" href="#">Switch Database <i class="fa fa-chevron-right fa-fw" aria-hidden="true"></i></a>
			        <ul class="dropdown-menu">
						<% current_project.databases.each do |d| %>		
							<li	data-toggle="tooltip" data-placement="right" 
								title="<%= d.failed? ? d.test_error[0..150] : d.testing? ? 'Testing...' : 'Connected' %>"> 
								<% if @script %>
									<%= link_to fa_icon('database', d.name, "db #{d.test_connection_status}"), db_sql_path(@script,d), 
									remote: true, method: :patch  %></li>
								<% else %>
									<%= link_to fa_icon('database', d.name, "db #{d.test_connection_status}"), d, remote: true  %></li>
								<% end %>
						<% end %>
			        </ul>
			      </li>
			</ul>	
		</div>
		<input type="text" id="js-db-search" placeholder="search..." class="form-control">
		
		<% @schema = params[:schema] || 'public' %>
		<div class="dropdown m-t browser-menu">
		  <button class="btn btn-default dropdown-toggle" type="button" id="schemaMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
		    <i class="fa fa-bars"> </i>
			<span class="header-label">Schema: <strong><%= @schema %></strong></span>
		    <span class="caret"></span>
		  </button>
		  <ul class="dropdown-menu" aria-labelledby="schemaMenu">
		    <% @database.tables.pluck(:schema).uniq.each do |s| %>
				<li class="<%= 'active' if s == @schema %>" >
					<%= link_to s, database_path(@database, schema: s), remote: true  %></li>
				</li>
			<% end %>
		  </ul>
		</div>
	</div>
	
	<div class="browser-panel-body">
		<% if @database.schema_failed? %>
			<div class="text-danger" style="word-break: break-all;"><small><%= @database.schema_error[0..400] %></small></div>
		<% end %>
		
		<% @database.tables.where(schema: @schema).order(name: :asc).each do |t| %>
		
			<button class="btn tree-node table-item" type="button" data-toggle="collapse" data-target="#columns_<%= t.id %>" 
				data-table-def="<%= (t.to_json) %>"
				aria-expanded="false" aria-controls="collapseExample">
				<% if t.view? %>
					<i class="fa fa-th fa-fw table_type_view" aria-hidden="true"></i>
				<% else %>
					<i class="fa fa-table fa-fw table_type_table" aria-hidden="true"></i>
				<% end %>
				<span class="db-table-name"><%= t.name %></span>
			</button>
			
						
			<ul class="table-columns collapse fa-ul" id="columns_<%= t.id %>">
				<% t.columns.sort_by{|c| c["name"]}.each do |c| %>
					<li class="table-column has-browse-tools" >
						<% case c["data_type"]
								   when "character varying", "varchar", "nvarchar", "text" %>
									   
								<i class="fa-li fa fa-fw fa-text-width" aria-hidden="true" ></i>
							<% when "character", "char", "nchar", "bpchar" %>
								<i class="fa-li fa fa-font fa-fw" aria-hidden="true"></i>
							<% when "integer", "smallint", "bigint","decimal","numeric", "real", "double precision" %>
								<i class="fa-li fa fa-fw text" aria-hidden="true">#</i>
							<% when "boolean" %>
								<i class="fa-li fa fa-fw fa-toggle-on" aria-hidden="true"></i>
							<% when "date" %>
								<i class="fa-li fa fa-calendar fa-fw" aria-hidden="true"></i>
							<% when "timestamp without time zone","timestamp", "timestamp with time zone" %>
								<i class="fa-li fa fa-clock-o fa-fw" aria-hidden="true"></i>
						<% end %>
						
						<span class="db-table-col-name" title="double click to add to editor"><%= c["name"] %></span>
						
					</li>
				<% end %>				
			</ul>
		<% end %>		
	</div>
</div>

<% if @database.tables.size == 0 && !@database.schema_failed? %>
<script>
	$(function(){
		$("#refresh-db-schema").trigger('click');	
	});
</script>
<% end %>


<ul class="dropdown-menu sql-context-menu" aria-labelledby="table-ctx-menu" id="table-context-menu" style="position:absolute; left:100px; top:100px;">
	<li><a href="#" onclick="lodr.sql.cx.select();">Select </a></li>			
	<li><a href="#" onclick="lodr.sql.cx.create();">Create</a></li>	
	<li><a href="#" onclick="lodr.sql.cx.drop();">Drop</a></li>	
	<li><a href="#" onclick="lodr.sql.cx.alter();">Alter</a></li>	
	<li role="separator" class="divider"></li>
	<li><a href="#" onclick="lodr.sql.cx.def();">Show Definition</a></li>
</ul>

<div class="modal fade" id="table-def-modal" tabindex="-1" role="dialog" aria-labelledby="tableDefModal">
  <div class="modal-dialog modal-md" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       
		<h4 class="modal-title">
			<span class="actual-title"> Modal title </span>
			<span class="label label-primary">table</span>
		</h4>		
      </div>
      <div class="modal-body">
	      <div class="modal-body-table">
		  
	      </div>
      </div>
	  <div class="modal-footer">
		  
	  </div>
    </div>
  </div>
</div>

	
	

app/views/databases/_database.html.erb
<%= form_for(@database, html: {class: "next-submit-form"}) do |f| %>

	<% if @database.errors.any? %>
	  <div id="error_explanation" class="alert alert-danger">
		  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
		  <span class="sr-only">Error:</span>
	      Please fix <%= pluralize(@database.errors.count, "error") %>
	  </div>
	<% end %>
	
		<div class="form-group">
			<%= f.label :name, "Target Name" %>
			<%= f.text_field :name, class: "form-control input-lg", placeholder: "A memorable name for easy reference" %>
		</div>
		
		<div class="form-group">
			<%= f.label :server, "Host Address / Server" %>
			<%= f.text_field :server, class: "form-control input-lg", placeholder: "IP Address or URL" %>
		</div>
		
		<div class="form-group">
			<%= f.label :port, "Port" %>
			<%= f.number_field :port, class: "form-control input-lg", placeholder: "5439" %>
		</div>
		
		<div class="form-group">
			<%= f.label :db_name, "Database Name" %>
			<%= f.text_field :db_name, class: "form-control input-lg", placeholder: "Name of your actual database" %>
		</div>
		
		<div class="form-group">
			<%= f.label :user_name, "User Name" %>
			<%= f.text_field :user_name, class: "form-control input-lg", 
				placeholder: "User name used to access the database" , autocomplete: "off"%>
			<p class="help-block">This user should have write access to the database specified above</p>
		</div>
		<div class="form-group">
			<%= f.label :password, "Password" %>
			<%= f.password_field :password, class: "form-control input-lg", placeholder: "Password", autocomplete: "off" %>
			<% unless @database.new_record? %>
			<p class="help-block">Leave password blank unless you intend to change it</p>
			<% end %>
		</div>
		
		<button class="btn btn-info-outline" type="button" data-toggle="collapse" data-target="#advanced" aria-expanded="false" aria-controls="advanced">
		  <i class="fa fa-expand"></i> Show Advanced Options
		</button>
		<br /> <br />
		<div class="collapse" id="advanced">
		  <div class="well">
			<div class="form-group">
				<%= f.label :properties, "Connection Properties" %>
				<% props={} ; props = JSON.parse @database.properties if @database.properties %>
				<table id="properties" class="no-borders table table-condensed">
					<% props.each_pair do |key,val|%>
						<tr class="keypair">
							<td><input class="form-control" type="text" placeholder="key" 
								name="props[key_<%= key %>]" 
								value="<%= key %>"></td>
							<td><input class="form-control" type="text" 
								placeholder="value" name="props[val_<%= key %>]"
								value="<%= val %>"></td>
							<td><a href="#" class="delete-prop btn btn-xs btn-danger"><span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span> </a></td>
						</tr>					
					<% end %>
					<tr class="keypair">
						<td><input class="form-control" type="text" placeholder="key" name="props[key_<%= props.size+1 %>]" ></td>
						<td><input class="form-control" type="text" placeholder="value" name="props[val_<%= props.size+1 %>]" ></td>
						<td><a href="#" class="delete-prop btn btn-xs btn-danger"><span class="glyphicon glyphicon-minus-sign" aria-hidden="true"></span> </a></td>
					</tr>					
				</table>
				
				<a href="#" id="add-prop" class="btn btn-sm btn-success">
					<span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Add</a>
			</div>  
			  
			  
			<div class="form-group">
				<%= f.label :jdbc_url, "Custom JDBC URL" %>
				<%= f.text_field :jdbc_url, class: "form-control", 
					placeholder: "jdbc:redshift://servername:5439/databasename" %>
				<p class="help-block">When present we will use this url to connect</p>
			</div>
		  </div>
		</div>
  	
  
  	<hr />
	<%= link_to "Cancel", @loader.nil? ? databases_path : loader_target_table_path(@loader), class: "btn btn-warning" %>
	<%= f.submit "Save", class: "btn btn-primary w-sm"%>
	
	<p class="help-block m-t">The database connection will be <strong>tested</strong> on Save</p>

<% end %>

<div class="m-b-lg"> &nbsp;</div>

app/views/databases/index.html.erb
<%= render 'shared/database_event' %>

<h1 class="page-title">Target Databases</h1>


<div class="row">
	<div class="col-xs-6">
		<%= link_to fa_icon("database","New Database"), new_database_path, class: "btn btn-sm btn-primary-outline"%>
	</div>
</div>

<br />

<table class="table table-striped table-hover">
	<thead><tr>
		<th>Target</th>
		<th>Server Host</th>
		<th>Port</th>
		<th>Database Name</th>
		<th>User Name</th>
		<th>Connection Status</th>
		<th>Error Message</th>
		<th>Actions</th>
	</tr></thead>
	
	<tbody>
		<% @databases.each do |t| %>
			<tr id="database_<%= t.id %>" data-target-id="<%= t.id %>" class="<%= t.test_connection_status %>">
				<td><%= link_to t.name, edit_database_path(t) %></td>
				<td class="nowrap-cell" title="<%= t.server %>"><%= t.server %></td>
				<td><%= t.port %></td>
				<td><%= t.db_name %></td>
				<td><%= t.user_name %></td>
				<td>
					<% if t.failed? %>
						<span class="label label-danger"><%= t.test_connection_status.capitalize %></span>
					<% elsif t.testing? %>
						<i class="fa fa-spinner fa-spin"></i>&nbsp;&nbsp;<span class="label label-warning"> <%= t.test_connection_status.capitalize %></span>
					<% else %>
						<span class="label label-success"><%= t.test_connection_status.capitalize %></span>
					<% end %>					
				</td>
				<td class="nowrap-cell"><a href="#" data-target="#errorModal" 
					data-toggle="modal"
					data-body="<%= t.test_error %>"><%= t.test_error %></a></td>
				<td><%= link_to fa_icon("trash","Delete"), database_path(t), method: :delete,
					data: {confirm: "Are your sure you want to delete target db connection \n\t #{t.name}"},
					class: "btn btn-xs btn-danger" %> </td>
			</tr>
		<% end %>
	</tbody>
</table>

<% if @databases.count ==0 %>
	<div class="embed-responsive embed-responsive-16by9">
		<iframe width="100%" height="100%" src="https://www.youtube.com/embed/N8MNJFt7CV4" frameborder="0" allowfullscreen></iframe>
	</div>
<% end %>

<div class="m-t-lg">
	<%= render 'database_ad_block' %>
</div>

<%= render 'shared/error_modal' %>

<script id="_database_row" type="text/x-handlebars-template">
	<td>{{{ name }}}</td>
	<td class="nowrap-cell" title="{{server}}">{{server}}</td>
	<td>{{ port }}</td>
	<td>{{ db_name }}</td>
	<td>{{ user_name }}</td>
	<td>
		{{{ status_html }}}					
	</td>
	<td class="nowrap-cell"><a href="#" data-target="#errorModal" data-toggle="modal" data-body="{{ test_error }}">{{ test_error }}</a></td>
	<td>
		{{{ delete_html }}}
	</td>
</script>

app/views/databases/refresh.js.erb
$(function(){
	if($("#database .dropdown-menu").is(":visible")){
		$('#database .browser-menu').trigger('click');
	}	
	if(lodr.sql.schema_fetch_timer){
		clearTimeout(lodr.sql.schema_fetch_timer);
	}
	
	$("#database .schema_status").remove();
	$("#database .browser-panel-header")
		.append('<div class="schema_status"><i class="fa fa-spinner fa-spin"></i> Fetching Schema... </div>');
	lodr.sql.schema_fetch_timer = setTimeout(function(){
		$.getScript('<%= database_path(@database) %>');
	}, (2500*Math.random()));	
});	

app/views/databases/show.js.erb
$(function(){
	if(lodr.sql.schema_fetch_timer){
		clearTimeout(lodr.sql.schema_fetch_timer);
	}
	
	// $("#database .browser-panel-body").empty();
	$("#database .browser-panel-header .header-label").text("<%= @database.name %>");
	$("#refresh-db-schema").attr('href', '<%= refresh_database_path(@database) %>');
	$("#edit-db-conn").attr('href', '<%= edit_database_path(@database) %>');
	
	<% if @database.schema_fetching? || @database.schema_status.nil? %>
		$("#database .schema_status").remove();
		$("#database .browser-panel-header")
			.append('<div class="schema_status"><i class="fa fa-spinner fa-spin"></i> Fetching Schema... </div>');
		
		lodr.sql.schema_fetch_timer = setTimeout(function(){
			$.getScript('<%= database_path(@database) %>');
		}, (2500*Math.random()));		
	<% elsif @database.schema_failed? %>
		$("#database .schema_status").remove();
		$("#database .browser-panel-header")
			.append('<div class="schema_status text-danger">' +
						'<i class="fa fa-exclamation-circle"></i> Schema Failed... </div>' +
					'<div class="text-danger"  style="word-break: break-all;" ><small><%= j(@database.schema_error[0..300]) %></small></div>');
	<% else %>
		$("#database").empty().append("<%= raw escape_javascript(render 'databases/browser') %>");
		$("#database .browser-panel-header")
				.append('<div class="schema_status text-success" style="word-break: break-all;" ><i class="fa fa-check-circle"></i> Fetched Schema </div>');
		
				
			setTimeout(function(){
				$(".schema_status").slideUp().delay(1500).remove();
				lodr.sql.resize();
			}, 5000);
	<% end %>
			
	lodr.sql.resize();
});

app/views/databases/status.js.erb
<% @databases.each do |t| %>
	$("#database_<%= t.id %>").html(
		lodr._target_row({
			name: '<%= link_to t.name, edit_database_path(t) %>'
			, server: "<%= t.server %>"
			, port: <%= t.port %>
			, db_name: "<%= t.db_name %>"
			, user_name: "<%= t.user_name %>"
			, status_html: 
					<% if t.failed? %>
						'<span class="label label-danger"><%= t.test_connection_status.capitalize %></span>'
					<% elsif t.testing? %>
						'<i class="fa fa-spinner fa-spin"></i>&nbsp;&nbsp;<span class="label label-warning"> <%= t.test_connection_status.capitalize %></span>'
					<% else %>
						'<span class="label label-success"><%= t.test_connection_status.capitalize %></span>'
					<% end %>
			, test_error: '<%= t.test_error.gsub("\n"," ") if t.test_error %>'
			, delete_html: '<%= link_to "Delete", database_path(t), method: :delete, data: {confirm: "Are your sure you want to delete target db connection #{t.name}"}, class: "btn btn-xs btn-danger" %>'
		})
	);
	
	<% unless t.testing? %>
		$("#database_<%= t.id %>").removeClass("testing");
	<% end %>
<% end %>