config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => :registrations }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'account' => 'account#show'
  get 'account/new' => 'account#new'
  get 'account/choose_plan/:id' => 'account#choose_plan', as: 'account_choose_plan'
  post 'account/subscribe' => 'account#subscribe', as: 'account_subscribe'
  delete 'account/cancel' => 'account#cancel', as: 'account_cancel'
  
  resources :projects do
    resources :invites, only: [:new, :create, :destroy]
  end
  
  # bucketloader for mass loading a bucket
  resources :bucket_loaders do
    delete 'destroy_multiple', on: :collection    
    get 'preview(/:id)', to: "bucket_loaders#preview", as: 'preview', on: :collection
    
    member do
      post 'run'
      delete 'cancel'
    end
    
    scope module: :bucket_loader do   
      resources :sources, :load_jobs, only: [:index, :show]
    end
  end
    
  # Source Files
  resources :sources do 
     collection do
         get 'dismiss' => 'sources#dismiss_zips', as: 'dismiss_zips'
         get 'upload' => 'sources#upload'
         get 'status/all' => 'sources#file_status', as: 'all_status'
         get 'status/zips' => 'sources#zips_status', as: 'zips_status' 
         delete 'delete' => 'sources#destroy_multiple'
         
         resources :s3_buckets do
            post 'add' => 's3_buckets#add', format: false, on: :member, as: 'add_file'            
            post 'add_multiple' => 's3_buckets#add_multiple_files', format: false, on: :member, as: 'add_multiple_files'            
            post 'load' => 's3_buckets#load', format: false, on: :member, as: 'load_file'
            get 'search' => 's3_buckets#search', format: false, on: :member 
         end
     end
  end
  
  # Target Databases
  resources :databases do
    patch 'refresh', on: :member
    get 'status', on: :collection
    
    resources :tables
  end  
  
  resources :sql, only: [:index,:show] do
    patch 'database/:database_id', to: 'sql#update_db', on: :member, as: 'db'
    collection do
      resources :scripts do
        resources :queries do
          delete '', to: 'queries#delete_all', on: :collection
        end
      end
    end
  end
  
  # Load Jobs
  get 'loaders/back/(:id)' => 'loaders#back', as: 'loader_back'
  get 'loaders' => 'loaders#index'
  get 'loaders/status/all' => 'loaders#status', as: 'all_status'
  get 'loaders/(:id)/sources' => 'loaders#sources', as: 'loader_sources'
  get 'loaders/(:id)/settings' => 'loaders#settings', as: 'loader_settings'
  get 'loaders/(:id)/transforms' => 'loaders#transforms', as: 'loader_transforms'
  get 'loaders/(:id)/target' => 'loaders#target_table', as: 'loader_target_table'
  get 'loaders/(:id)/summary' => 'loaders#summary', as: 'loader_summary'
  get 'loaders/new' => 'loaders#new', as: 'new_loader'
  get 'loaders/:source_id/load' => 'loaders#load_source', as: 'loader_load_source'
  get 'loaders/:id/edit' => 'loaders#edit', as: 'edit_loader'
  get 'loaders/:id/show' => 'loaders#show', as: 'show_loader'
  delete 'loaders/:id' => 'loaders#destroy', as: 'delete_loader'
  patch 'loaders/:id/sources' => 'loaders#update_sources', as: 'update_loader_sources'
  patch 'loaders/:id/settings' => 'loaders#update_settings', as: 'update_loader_settings'
  patch 'loaders/:id/transform' => 'loaders#update_transform', as: 'update_loader_transform'
  patch 'loaders/:id/target' => 'loaders#update_target', as: 'update_loader_target'
  patch 'loaders/:id/schedule' => 'loaders#update_schedule', as: 'update_loader_schedule'
  get 'loaders/wait' => 'loaders#wait', as: 'loader_wait'
  patch 'loaders/exit' => 'loaders#exit', as: 'exit_loader', format: false
  get 'loaders/exit' => 'loaders#exit_wizzard', as: 'exit_wizzard', format: false
  get 'loaders/:id/run' => 'loaders#run', as: 'loader_run'
  get 'loaders/:id/cancel' => 'loaders#cancel', as: 'loader_cancel'
  post 'loaders/delete' => 'loaders#destroy_multiple', as: 'destroy_loaders'
  post 'loaders/run' => 'loaders#run_multiple', as: 'run_loaders'
  
  get 'dashboard' => 'dashboard#index'
  get 'dashboard/stats' => 'dashboard#stats'
  
  namespace :api do
      scope :hooks, as: 'hooks' do
        post 'stripe', to: 'webhooks#stripe_event'
      end
      
      namespace :xo do
         resources :load_jobs, only: [:update]
         resources :zip_files, only: [:update]
         get 'canary', to: 'load_jobs#canary'
         
         put 'db_requests/query/:id' => 'db_requests#query', as: 'db_query'
         put 'db_requests/schema/:id'=> 'db_requests#schema', as: 'db_schema'
         put 'db_requests/table/:id' => 'db_requests#table', as: 'db_table'
      end
      
      namespace :v1 do
        resources :jobs, only: [:index, :destroy, :show] do
          post ':loader_id/run' => 'jobs#run', on: :collection
        end
        resources :bucket_jobs, only: [:index, :destroy, :show] do
          post ':bucket_loader_id/run' => 'bucket_jobs#run', on: :collection
        end
      end
  end
  
  # Admin routes
  namespace :admin do
    get 'console', to: 'console#index'
    get 'console/:id/show', to: 'console#show'
    get 'console/load_jobs'
    get 'console/queries'
    get 'console/zips'
    get 'console/sources'
    get 'console/databases'
    delete 'cancel_long', to: 'console#cancel_long_running_jobs'
    delete 'cancel_all', to: 'console#cancel_all_jobs'
    delete 'cancel/:id', to: 'console#cancel', as: 'cancel'
    delete 'cancel_unzip/:id', to: 'console#cancel_unzip', as: 'cancel_unzip'
  end
  
  # static high voltage pages
  # this has to be at the bottom of routes file
  # or else it will block all other routes
  get "/*id" => 'pages#show', as: :page, format: false
  root to: 'pages#show', id: 'home'
end

app/models/loader.rb
require "#{Rails.application.config.root}/lib/wrangler"

class Loader < ApplicationRecord
  belongs_to :project
  belongs_to :user
  belongs_to :database
  belongs_to :bucket_loader
  
  # this has to come before load jobs
  # dependency related destroy callbacks
  # get fired
  before_destroy :cancel, :remove_scheduled_jobs
  
  has_many :load_jobs, dependent: :nullify
  has_many :loader_sources, dependent: :destroy
  has_many :source_files, through: :loader_sources
  
  accepts_nested_attributes_for :source_files, allow_destroy: true
  
  # Loader create stage
  enum step: [:choose_inputs,:loader_settings, :transformations, :target_table, :summary, :ready]
  
  # Redshift Distribution Style
  enum distribution_style: [:dist_key, :dist_even, :dist_all]
  
  # File update mode for ongoing runs
  #   of load job
  enum update_mode: [:mode_replace, :mode_append, :mode_merge]
  
  # Multi file uploads. This is where a loader
  #   ingests multiple files for a single target
  #   table
  enum multi_file_mode: [:multi_mode_union, :multi_mode_append, :multi_mode_merge, :multi_mode_join]
  
  # Schedule types
  include Scheduled
  # Authorize project associations
  include AuthorizeProject  
  
  before_save :set_name_and_target_table, :set_column_settings_when_blank
  before_validation :reject_blanks
  validates :name, :user, :project, presence: true
    
  # validate the wizard in phases
  # After sources are chosen
  validate :sources_are_valid?, if: :loader_settings?
  validate :transformations_are_valid?, if: :target_table?
  validate :target_table_is_valid?, if: :summary?
  validate :schedule_valid?, if: :summary?
  validate :loader_is_valid?, if: :ready?
  
  def self.search(search)
    unless search.blank?
      where('lower(name) LIKE ?', "%#{search.downcase}%")
    else
      order(created_at: :desc)
    end
  end
  
  def estimated_input_rows
    @estimated_rows ||= self.source_files.where.not(rows: nil).sum(:rows)
  end
  
  def will_exceed_quota?
    if Rails.application.secrets[:on_prem]
      false
    else
      self.project.owner.update_subscription_parameters
      estimated_input_rows > self.project.owner.subscription.rows_remaining
    end
  end
  
  def is_running?(excluding = nil)
    l = self.load_jobs.where(status: [:running,:queued]).where.not(id: excluding).count
    return l>0
  end
  
  # checks if loader is valid
  # active, and isn't already running
  def is_runnable?(excluding = nil)
    self.active && loader_is_valid? && !is_running?(excluding)
  end
  
  def cancel
    jobs = self.load_jobs.where(status: [:running,:queued])
    jobs.each do |l|
      begin
        logger.info "Cancelling job: #{l.job_id}"
        resp = HTTParty.get("#{Wrangler::END_POINTS[:cancel_job]}#{l.job_id}")
      rescue => e
        logger.error "Failed to cancel job #{l.job_id} \n #{e.message}"
      end
     end
     
     jobs.update_all(status: :cancelled, 
       finished_at: Time.now,
       info: "Job was cancelled")
  end
  
  def remove_scheduled_jobs
    LoadJob.where(loader_id: self.id, status: :scheduled).destroy_all unless self.id.nil?
  end
    
  def sources_are_valid?
      if self.source_files.size ==0
        errors.add(:source_files, " - choose at least 1 source file")
        return errors.empty?
      end 
      
      file_headers = []
      # limiting checked source files
      # 15 due to out of memory when using
      # large file sets from bucket loaders
      sfiles = self.source_files.limit(15)
      sfiles.each do |f| 
          if f.failed?
              self.errors.add(:invalid_files, " - #{f.name} failed pre processing")
          end
          file_headers.push( fetch_column_names(f) )
      end
            
      size = file_headers.first.size
      if file_headers.any?{ |f| f.size != size }
          self.errors.add(:columns, " - all source files should have the same number of columns")
      end
      
      file_headers = file_headers.flatten.uniq
      sfiles.each do |f|
          hd = fetch_column_names(f)
          diff = file_headers - hd
          if diff.size >0
              self.errors.add(:columns, " - all source files should have the same columns. #{f.name} is missing these columns #{diff}")
          end
      end
      
      if self.use_file_prefix 
        if self.source_files.count > 1
          self.errors.add(:source_files, " - only 1 source file can be selected when loading the latest matching file based on a prefix.")
        end
        
        if self.file_prefix.blank?
          self.errors.add(:source_files, " - please enter a file prefix")
        end
      end
      
      errors.empty?      
  end
  
  def has_source_errors?
     (errors.keys & [:source_files,:invalid_files,:columns]).any?
  end
  
  def transformations_are_valid?
     errors.add(:column_settings, " - invalid column settings") if column_settings.blank? 
     errors.empty?
  end
  
  def has_transform_errors?
     errors.keys.include? :column_settings
  end
  
  def has_schedule_errors?
     (errors.keys & [:start_time,:start_date, :time_zone]).any?
  end
  
  def target_table_is_valid?    
      [:target_table_name, :database_id, :update_mode, :distribution_style].each do |a|
         errors.add(a, " must be present ") if send(a).blank? 
      end
      
      authorized_project?
      
      errors.add(:target_table_name, " - must start with letter character") if target_table_name && target_table_name.first.match(/\d/)
      errors.add(:target_table_name, " - spaces, quotes, exclamations are not allowed ") if target_table_name && target_table_name.match(/[\'\"\s!]/)
      errors.add(:merge_keys, " - choose at least 1 merge key") if (merge_keys.nil? || merge_keys.size == 0) && mode_merge?
      errors.add(:distribution_key, " - choose a distribution key for a Key based distribution style") if dist_key? && distribution_key.nil?
      errors.empty?
  end
  
  def has_target_errors?
     (errors.keys & [:target_table_name, :database_id, 
         :update_mode, :distribution_style, :merge_key, :distribution_key]).any?
  end
  
  def loader_is_valid?
      sources_are_valid?
      transformations_are_valid?
      target_table_is_valid?
      errors.empty?
  end
  
  # Check box collection form is
  # sending a blank value in addition
  # to the actuals. Need to clear the
  # blanks before validation
  def reject_blanks
      self.merge_keys.reject! {|k| k.blank? || k=="0" || k==0 } if self.merge_keys
      self.sort_keys.reject! {|k| k.blank? || k=="0" || k==0 } if self.sort_keys
      self.primary_keys.reject! {|k| k.blank? || k=="0" || k==0 } if self.primary_keys
      
      self.distribution_key = nil if !dist_key?
  end
  
  def self.next_step(istep)
     if istep == :choose_inputs
         :loader_settings
     elsif istep == :loader_settings
         :transformations
     elsif istep == :transformations
         :target_table
     else
         :summary
     end 
  end
  
  def self.namify(name)
     s = name.split("_")
     s[s.size-1].capitalize
  end
  
  def last_run
     @last_run ||= load_jobs.where.not(status: :scheduled).order(updated_at: :asc).last 
  end
  
  def headers
    if self.column_settings && @headers.nil?
        @headers = self.parsed_column_settings.collect { |m| m["columnName"] }
    end
        
    return @headers || []
  end
  
  def parsed_column_settings     
     @parsed_column_settings ||= JSON.parse(self.column_settings || "[]")
  end  
  
  def to_ll
     ll = {
         useFilePrefix: self.use_file_prefix,
         filePrefix: self.file_prefix,
         originalColumnNames: fetch_column_names(self.source_files.first),
         tableName: self.target_table_name,
         loadMode: update_mode_to_ll,
         primaryKeys: self.primary_keys,
         mergeKeys: self.merge_keys,
         sortKeys: self.sort_keys,
         distKey: self.distribution_key,
         distStyle: self.distribution_style.split("_").last.upcase,
         preSql: self.pre_sql,
         postSql: self.post_sql
     }
     ll[:columnInfos] = JSON.parse(self.column_settings) if self.column_settings
     ll[:wrangleScript] =  JSON.parse(self.transformations) if self.transformations
     ll[:connInfo] = self.database.to_ll if self.database
     return ll
  end
  
  def update_mode_to_ll
      update_mode.split("_")[1].upcase
  end
  
  def contains(meth_sym, item)
    array_container = self.send(meth_sym)
    !array_container.blank? && array_container.include?(item)
  end
  
  def set_column_settings_when_blank
    if self.parsed_column_settings.size == 0 || self.parsed_column_settings[0]["columnName"].nil?
      sf = self.source_files.first
      self.column_settings = sf.headers if sf
    end
  end
  
  private
  
  def fetch_column_names(f)
     hd = f.parsed_headers.collect{ |hd| 
            if hd.class == String
                hd.strip
            else
               hd["columnName"].strip  
            end                 
     }
     return hd
  end
  
  def set_name_and_target_table
      sf = self.source_files.first
      if sf && self.name == "Untitled"           
          self.name = "Load " + sf.clean_name 
      end
      
      if sf && self.target_table_name.nil?           
          self.target_table_name = sf.name.split("/").last.split(".").first
          self.target_table_name.gsub!(/[^[:alnum:]_,$]/,"_")
          self.target_table_name.gsub!(/_+/, "_")
          if self.target_table_name.first.match(/\d/)
            self.target_table_name = "l_" + self.target_table_name
          end
      end
  end
  
end

app/models/project.rb
class Project < ApplicationRecord
  
  # this must be ahead of the dependent
  # stuff so it will validate first
  before_destroy :check_destroyable
  
  has_many :loaders, dependent: :destroy
  has_many :bucket_loaders, dependent: :destroy
  has_many :load_jobs, dependent: :destroy
  
  
  has_many :scripts, dependent: :destroy
  has_many :databases, dependent: :destroy  
  has_many :source_files, dependent: :destroy
  has_many :zip_files, dependent: :destroy
  has_many :s3_buckets, dependent: :destroy
  
  has_many :project_users, dependent: :destroy
  has_many :users, -> { distinct }, through: :project_users
  has_many :queries, through: :scripts
  has_many :bucket_load_histories, through: :bucket_loaders
  
  belongs_to :owner, class_name: "User"
  
  # Field Encryption
  include EncryptedFields 
  attr_encrypted :api_token, key: :encryption_key
  
  validates :name, :owner, :time_zone, presence: true
  after_create :add_owner_project_user
  
  before_save :generate_token, unless: :api_token  
  
  def generate_token
    loop do
        self.api_token = SecureRandom.urlsafe_base64(nil, false)
        break unless self.class.exists?(encrypted_api_token: self.encrypted_api_token )
    end
  end
  
  def add_owner_project_user
    self.users << self.owner
  end
  
  def can_destroy_project?(user)
    if user.id == owner.id && owner.projects.count > 1
      true
    else
      false
    end
  end
  
  private
  
  def check_destroyable
    throw(:abort) unless self.owner_id ==-99 || can_destroy_project?(self.owner)
  end
  
end

app/helpers/loaders_helper.rb
module LoadersHelper
  LodrObject = Struct.new(:text,:value)
  
  def array_to_collection(arry)
    col = []
    arry.each do |e|
      next if e.blank?
      
      l = LodrObject.new(e.to_s.split("_").last.titleize, e.downcase.to_sym)
      col << l      
    end
    
    col
  end

end

app/views/loaders/_loader.html.erb
<div class="row">
	<div class="col-md-4">
		
		<div class="row">
			<div class="col-sm-3 text-center icon-ctr checkbox-inline">
				<%= check_box_tag 'loader_ids[]', loader.id, false, class: "input-lg"%>	 
				  <% if loader.active %>
				  	<% if loader.is_running? %>
  	  				  <span class="fa-stack fa-lg text-success" title="there is an active load job running">
  	  				    <i class="fa fa-circle-thin fa-stack-2x"></i>
  	  					<i class="fa fa-chevron-right fa-stack-1x"></i>
  	  				  </span>
					<% elsif loader.scheduled? %>
	  				  <span class="fa-stack fa-lg text-warning" title="job is ready to be run">
	  				    <i class="fa fa-circle-thin fa-stack-2x"></i>
	  					<i class="fa fa-calendar fa-stack-1x"></i>
	  				  </span>
					<% else %>
	  				  <span class="fa-stack fa-lg text-info" title="job is ready to be run">
	  				    <i class="fa fa-circle-thin fa-stack-2x"></i>
	  					<i class="fa fa-upload fa-stack-1x"></i>
	  				  </span>
					<% end %>
				  <% else%>
					  <span class="fa-stack fa-lg text-muted">
					    <i class="fa fa-circle-thin fa-stack-2x"></i>
						<i class="fa fa-pencil fa-stack-1x"></i>
					  </span> 
				  <% end %>						  
			</div>
			<div class="col-sm-9">
				<h4 class="title"><%= link_to loader.name, show_loader_path(loader) %></h4>
				<p class="text-muted"><i class="fa fa-clock-o" aria-hidden="true"></i>
					<% if loader.last_run %> 
						ran <%= time_ago_in_words(loader.last_run.created_at) %> ago
					<% else %>
						edited <%= time_ago_in_words(loader.updated_at) %> ago
					<% end %>
					</p>
					
				<p class="text-muted"><i class="fa fa-hand-o-right" aria-hidden="true"></i>
					update mode <span class="text-info"><%= loader.update_mode.split("_").last.capitalize %></span>
				</p>
					
			   <% if loader.last_run %>
				<div class="loader-status">
					<% if loader.last_run.queued? %>
						<span class="label label-info <%= loader.last_run.status %>" 
							data-loader-id="<%= loader.id %>" >Queued</span>&nbsp;<i class="fa fa-spinner fa-spin"></i>
					<% elsif loader.last_run.running? %>
						<span class="label label-info <%= loader.last_run.status %>"
							data-loader-id="<%= loader.id %>"  >Running</span>&nbsp;<i class="fa fa-spinner fa-spin"></i>		
					<% elsif loader.last_run.succeeded_with_errors? %>
						<span class="label label-warning <%= loader.last_run.status %>"
							data-loader-id="<%= loader.id %>"  >Succeeded with Errors</span>
					<% elsif loader.last_run.succeeded? %>
						<span class="label label-success <%= loader.last_run.status %>"
							data-loader-id="<%= loader.id %>"  >Succeeded</span>
					<% elsif loader.last_run.failed? %>
						<span class="label label-danger <%= loader.last_run.status %>"
							data-loader-id="<%= loader.id %>"  >Failed  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span></span>
					<% elsif loader.last_run.scheduled? %>
						<span class="label label-warning <%= loader.last_run.status %>"
							data-loader-id="<%= loader.id %>"  >Scheduled </span>
					<% else %>
						<span class="label label-warning <%= loader.last_run.status %>"
							data-loader-id="<%= loader.id %>"  ><%= loader.last_run.status.titleize %> <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span></span>
					<% end %>
				</div>				
				<% end %>
				
			</div>
		</div>
				
	</div> 
	
	<div class="col-md-8">
		<% unless loader.last_run.nil? %>
			<div class="row">
				<div class="col-md-4">
					<div class="statcard p-a">
					  <h3 class="statcard-number"><%= number_to_human (loader.last_run.input_rows || 0), units: num_units %></h3>
					  <span class="statcard-desc">PROCESSED ROWS</span>
					</div>
				</div>
				<div class="col-md-4">
					<div class="statcard p-a">
					  <h3 class="statcard-number"><%= number_to_human loader.last_run.duration, units: num_units %></h3>
					  <span class="statcard-desc">DURATION (SECS)</span>
					</div>
				</div>
				<div class="col-md-4">
					<div class="statcard p-a">
					  <h3 class="statcard-number"><%= number_to_human loader.last_run.rows_per_second, units: num_units %></h3>
					  <span class="statcard-desc">ROWS PER SECOND</span>
					</div>
				</div>
			</div>
		<% end %>
		
		<div class="row">
			<div class="col-md-4">
				<div class="titled-label p-l">
					<label class="label"><i class="fa fa-table" aria-hidden="true"></i> &nbsp;TARGET TABLE</label>
					<h5 title="<%= loader.target_table_name %>"><%= loader.target_table_name %></h5>
				</div>
			</div>
			<div class="col-md-4">
				<div class="titled-label p-l">
					<label class="label"><i class="fa fa-database" aria-hidden="true"></i> &nbsp;DATABASE</label>
					<h5 title="<%= loader.database ? loader.database.name : "Unknown" %>"><%= loader.database ? loader.database.name : "Unknown" %></h5>
				</div>
			</div>
			<div class="col-md-4">
				<div class="titled-label p-l">
					<label class="label"></i> COLUMNS</label>
					<h5><%= loader.parsed_column_settings ? loader.parsed_column_settings.size : 0 %></h5>
				</div>
			</div>
		</div>
		
	</div>
	
		
</div>

<div class="row m-t">
	<div class="col-md-offset-1 col-md-7">
		
		<% if loader.last_run && loader.last_run.info %>
			<div class="alert alert-warning">
				<h6>Last Run Info</h6>
				<p class="text-warning"><i class="fa fa-info-circle" aria-hidden="true"></i> &nbsp;<%= loader.last_run.info %></p>
			</div>
		<% end %>
	
		<% if loader.last_run && loader.last_run.execution_errors %>
		<div class="alert alert-danger">
			<strong>Error! </strong> <a href="#" data-target="#errorModal" 
					data-toggle="modal"
					data-body="<%= loader.last_run.execution_errors %>"><%= loader.last_run.execution_errors[0..100] %> </a>
		</div>
		<% end %>
			
		<div class="btn-group btn-group-sm m-b" role="group" aria-label="...">
			<% if loader.active && !loader.is_running? %> 
				<%= link_to(fa_icon("play-circle", "Run"), loader_run_path(loader), class: "btn btn-default",style: "text-align:left;") %>
			<% end %>
			
			<%= link_to fa_icon("eye", "View"), show_loader_path(loader), class:"btn btn-default" ,style: "text-align:left;" %>
			<%= link_to(fa_icon("pencil", "Edit"), edit_loader_path(loader), class: "btn btn-default",style: "text-align:left;") %>
			<%= link_to(fa_icon("clone", "Copy"), new_loader_path(loader_id: loader.id), class: "btn btn-default",style: "text-align:left;") %>
			<%= link_to(fa_icon("trash", "Delete"), delete_loader_path(loader), 
				class: "btn btn-default",style: "text-align:left;",
				data: {confirm: "Are you sure you want to delete this loader?"}, method: :delete) %>
			<% if loader.is_running? %>
			 	<%= link_to(fa_icon("ban", "Cancel"),loader_cancel_path(loader),
					class: "btn btn-sm btn-danger-outline ",style: "text-align:left;",
					data: {confirm: "Are you sure you want to cancel this load?"}) %>
			<% end %>			
		</div>
		
	</div>
	
</div>

app/views/loaders/index.html.erb
<div class="m-y loader-tabs">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Loaders</a></li>
    <li role="presentation"><%= link_to "Bucket Loaders", bucket_loaders_path %></li>
  </ul>

  <div class="tab-content p-a-md p-x-lg">

<h1 class="page-title">Loaders</h1>

<div class="row">
	<div class="col-sm-6">
		<div class="btn-toolbar">
			<a class="btn btn-default check-all" data-checked="false" data-check-all-target=".check-enable"> <i class="fa fa-square-o fa-1x" aria-hidden="true"></i></a>
			
			<%= link_to fa_icon("upload", "New Loader"), new_loader_path, class: "btn btn-sm btn-primary" %>
			<%= link_to fa_icon("trash", "Delete Selected"), "#", 
				class: "btn btn-sm btn-danger-outline hidden check-enable",
				data: {"check-all-form" => "#destroy_loaders" } %>
			<%= link_to fa_icon("play-circle", "Run"), "#", 
				class: "btn btn-sm btn-danger-outline hidden check-enable",
				data: {"check-all-form" => "#run_loaders" } %>
		</div>
	</div>
	<div class="col-sm-6 text-right">
		
		<%= form_tag(loaders_path, method: "get", class: "form-inline") do %>
		<div class="form-group">
		  <%= text_field_tag(:search, params[:search], class: "form-control", placeholder: "search sources") %>
		</div>
		  <%= submit_tag "Search", class: "btn btn-sm btn-default-outline" %>
		<% end %>
	</div>
</div>


<br />

<%= form_tag destroy_loaders_path, id: "destroy_loaders" do %>
<% end %>

<%= form_tag run_loaders_path, id: "run_loaders" do %>
<% end %>

<%= form_tag "", id: "main-check-all-form" do %>
<div class="lodr-table list-group">
	
	<% if @loaders.count ==0 %>
		<% if params[:search].blank? %>
			<div class="embed-responsive embed-responsive-16by9">
				<iframe width="100%" height="100%" src="https://www.youtube.com/embed/0bbNhQdK_Ck" frameborder="0" allowfullscreen></iframe>
			</div>
		<% else %>
			<div class="alert p-a-lg alert-warning">
				<i class="fa fa-exclamation-triangle"></i>
				<strong>Oh oh,</strong> we could not find any loaders with a name containing <strong><%= params[:search] %></strong>
			</div>
		<% end %>
	<% end %>
	
	<% @loaders.each do |loader| %>
		<div class="list-group-item input-file" id="loader_<%= loader.id %>" data-loader-id="<%= loader.id %>" >
			<%= render loader %>
		</div>
	<% end %>
</div>
<% end %>

</div> <!-- end tab content -->
</div> <!-- end tabs -->

<%= will_paginate @loaders %>

<% if @loaders.size > 0 %>
	<%= select_tag :per_page, options_for_select([10,25,50,100], @per_page),
			class: "form-control pull-right", style: "width:50px",
	       :onchange => "if(this.value){window.location=window.location+'?&per_page='+this.value;}" %>
<% end %>

<%= render 'shared/error_modal' %>